// AUTO-GENERATED BY SOVEREIGN DIGITAL TWIN COMPILER (PRISMA SCHEMA CONFORMANT)
// Target Component: digital_twin/DynamicThreeTwinViewer.tsx
// Property: Blue Waves Residence (test-apt-2bhk)

export interface SpatialBox {
  x: number;
  y: number;
  z: number;
  w: number;
  d: number;
  h: number;
}

export interface StagedFurniture {
  id: string;
  name: string;
  type: string;
  position: [number, number, number];
  size: [number, number, number];
  materialKey: string;
  color?: string;
  rotationY?: number;
}

export interface InspectionDefectPin {
  id: string;
  roomId: string;
  roomName: string;
  type: string;
  severity: string;
  position: [number, number, number];
  color: string;
  description: string;
  floorLevel: number;
}

export interface DigitalTwinRoom {
  id: string;
  name: string;
  category?: string;
  dimensions: string;
  carpetSqft: number;
  highlight: string;
  floorType: string;
  floorColor: string;
  wallColor: string;
  floorLevel?: number;
  bounds: SpatialBox;
  furniture: StagedFurniture[];
  lights?: Array<{ position: [number, number, number]; color: string; intensity: number; distance: number }>;
  defects?: InspectionDefectPin[];
}

export interface StructuralWall {
  id: string;
  position: [number, number, number];
  size: [number, number, number];
  materialKey: string;
  isExterior?: boolean;
  floorLevel?: number;
}

export interface DoorSpecification {
  id: string;
  name: string;
  position: [number, number, number];
  size: [number, number, number];
  rotationY: number;
  floorLevel: number;
  doorType: string;
  openAngle?: number;
  panelsCount?: number;
  frameMaterial: string;
  leafMaterial?: string;
}

export interface WindowSpecification {
  id: string;
  name: string;
  position: [number, number, number];
  size: [number, number];
  rotationY: number;
  sillHeight: number;
  floorLevel: number;
  hasMullions: boolean;
  frameMaterial: string;
}

export interface BalconySpecification {
  id: string;
  name: string;
  floorLevel: number;
  bounds: SpatialBox;
  deckMaterial: string;
  railings: Array<{
    id: string;
    position: [number, number, number];
    size: [number, number];
    rotationY: number;
    type: string;
    handrail?: boolean;
  }>;
}

export interface GlassPanel {
  id: string;
  position: [number, number, number];
  size: [number, number];
  rotationY?: number;
  floorLevel?: number;
  handrail?: boolean;
}

export interface CameraFocalTarget {
  target: [number, number, number];
  theta: number;
  phi: number;
  radius: number;
  walk: [number, number, number];
}

export interface TourWaypoint {
  p: [number, number, number];
  l: [number, number, number];
  label: string;
}

export interface FloorLevelSpec {
  id: string;
  name: string;
  elevation: number;
  roomIds: string[];
}

export interface DigitalTwinBlueprint {
  propertyId: string;
  publicId?: string;
  propertyTitle: string;
  locality?: string;
  city: string;
  state: string;
  propertyType?: string;
  configuration?: string;
  bhkCount?: number;
  conditionScore: number;
  carpetSqft: number;
  builtUpSqft: number;
  floor?: string;
  floorHeight: string;
  flooring?: string;
  furnishing?: string;
  facing?: string;
  views?: string[];
  balconyCount?: number;
  bathroomsCount?: number;
  efficiency: number;
  orientation: string;
  archetype?: string;
  levelsCount?: number;
  aboutSummary?: string;
  environmentalTheme: string;
  sunlightDirection?: [number, number, number];
  sunlightColor?: string;
  defects?: InspectionDefectPin[];
  floors?: FloorLevelSpec[];
  rooms: DigitalTwinRoom[];
  structuralWalls: StructuralWall[];
  doors?: DoorSpecification[];
  windows?: WindowSpecification[];
  balconies?: BalconySpecification[];
  glassPanels: GlassPanel[];
  focalTargets: Record<string, CameraFocalTarget>;
  waypoints: TourWaypoint[];
  fixtures: Array<{ item: string; detail: string; included: boolean }>;
}

export const TEST_APT_2BHK_BLUEPRINT: DigitalTwinBlueprint = {
  "propertyId": "test-apt-2bhk",
  "publicId": "prop_test-apt-2bh",
  "propertyTitle": "Blue Waves Residence",
  "locality": "Prime Corridor",
  "city": "Mumbai",
  "state": "Maharashtra",
  "propertyType": "APARTMENT",
  "configuration": "2 BHK",
  "bhkCount": 2,
  "carpetSqft": 1400,
  "builtUpSqft": 1792,
  "floor": "8th Floor",
  "floorHeight": "10.5 ft",
  "flooring": "VITRIFIED_TILES",
  "furnishing": "FULLY_FURNISHED",
  "facing": "EAST",
  "views": [
    "CITY",
    "GARDEN"
  ],
  "balconyCount": 1,
  "bathroomsCount": 2,
  "conditionScore": 9.6,
  "efficiency": 84,
  "orientation": "East-Facing",
  "archetype": "apartment",
  "levelsCount": 1,
  "environmentalTheme": "mumbai_coast",
  "sunlightDirection": [
    18.0,
    14.0,
    16.0
  ],
  "sunlightColor": "#FFF2DE",
  "aboutSummary": "DB Digital Twin: 'Blue Waves Residence'. Schema: APARTMENT (2 BHK), 1,400 sq.ft on 8th Floor. Flooring: Matte Vitrified Architectural Tiles (1200x600mm). Furnishing: FULLY_FURNISHED. Facing: EAST. Views: CITY, GARDEN. BIM layout strictly allocates 2 bedrooms with calibrated 3:1 hall-to-kitchen ratio. Civil inspection audit: Clean structure (9.6/10).",
  "defects": [],
  "floors": [
    {
      "id": "floor_0",
      "name": "Apartment Level",
      "elevation": 0.0,
      "roomIds": [
        "living",
        "kitchen",
        "balcony",
        "master"
      ]
    }
  ],
  "rooms": [
    {
      "id": "living",
      "name": "Grand Living & Dining Pavilion",
      "category": "LIVING_ROOM",
      "floorLevel": 0,
      "dimensions": "24' x 19'",
      "carpetSqft": 462,
      "highlight": "Matte Vitrified Architectural Tiles (1200x600mm) floors with floor-to-ceiling panoramic glass facade",
      "floorType": "Matte Vitrified Architectural Tiles (1200x600mm)",
      "floorColor": "#ECE9E2",
      "wallColor": "#F1EEE7",
      "bounds": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0,
        "w": 7.6,
        "d": 5.8,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "sofa_main",
          "name": "Curved Designer Italian Sofa",
          "type": "sofa",
          "position": [
            -0.8,
            0.42,
            1.8
          ],
          "size": [
            4.2,
            0.75,
            1.8
          ],
          "materialKey": "sofa",
          "color": "#D9D1C0"
        },
        {
          "id": "coffee_tbl",
          "name": "Matte Coffee Table",
          "type": "table",
          "position": [
            -0.8,
            0.25,
            0.4
          ],
          "size": [
            2.2,
            0.45,
            1.1
          ],
          "materialKey": "white",
          "color": "#FAFAF6"
        },
        {
          "id": "living_rug",
          "name": "Silken Area Rug",
          "type": "rug",
          "position": [
            -0.8,
            0.02,
            1.1
          ],
          "size": [
            5.2,
            0.02,
            3.6
          ],
          "materialKey": "rug",
          "color": "#CABFA8"
        },
        {
          "id": "dining_tbl",
          "name": "Dining Table & Chairs",
          "type": "table",
          "position": [
            2.6,
            0.45,
            -1.0
          ],
          "size": [
            2.4,
            0.85,
            1.2
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        },
        {
          "id": "tv_console",
          "name": "Floating Media Credenza",
          "type": "tv_unit",
          "position": [
            -0.8,
            0.3,
            -3.0
          ],
          "size": [
            3.4,
            0.6,
            0.5
          ],
          "materialKey": "dark",
          "color": "#3A3A40"
        }
      ],
      "lights": [
        {
          "position": [
            -0.8,
            2.8,
            1.0
          ],
          "color": "#FFD9A0",
          "intensity": 0.9,
          "distance": 12.0
        }
      ]
    },
    {
      "id": "kitchen",
      "name": "Culinary Studio & Island Kitchen",
      "category": "KITCHEN",
      "floorLevel": 0,
      "dimensions": "11' x 12'",
      "carpetSqft": 154,
      "highlight": "Quartz central island with integrated gas/induction burners & soft-close Blum joinery",
      "floorType": "Honed Nero Impala Granite & Quartzite",
      "floorColor": "#263238",
      "wallColor": "#F1EEE7",
      "bounds": {
        "x": 5.8,
        "y": 0.0,
        "z": -0.6,
        "w": 3.6,
        "d": 3.9,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "k_island",
          "name": "Quartz Island Prep Counter",
          "type": "counter",
          "position": [
            5.8,
            0.48,
            -0.6
          ],
          "size": [
            3.0,
            0.95,
            1.3
          ],
          "materialKey": "counter",
          "color": "#8D6F50"
        },
        {
          "id": "k_stools",
          "name": "Breakfast Bar Stools",
          "type": "stool",
          "position": [
            5.8,
            0.38,
            -1.8
          ],
          "size": [
            2.2,
            0.75,
            0.45
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        }
      ],
      "lights": [
        {
          "position": [
            5.8,
            2.8,
            -0.6
          ],
          "color": "#FFFFFF",
          "intensity": 0.85,
          "distance": 10.0
        }
      ]
    },
    {
      "id": "balcony",
      "name": "Covered Sky Deck & Balcony",
      "category": "BALCONY",
      "floorLevel": 0,
      "dimensions": "17' x 11'",
      "carpetSqft": 140,
      "highlight": "Open vista (CITY, GARDEN) with frameless tempered glass balustrade & teak deck",
      "floorType": "Weatherproof Teak Composite Deck",
      "floorColor": "#A87042",
      "wallColor": "#F1EEE7",
      "bounds": {
        "x": 1.8,
        "y": 0.0,
        "z": 4.6,
        "w": 5.3,
        "d": 3.4,
        "h": 1.1
      },
      "furniture": [
        {
          "id": "b_lounge",
          "name": "Weatherproof Balcony Loveseat",
          "type": "chair",
          "position": [
            1.8,
            0.35,
            4.199999999999999
          ],
          "size": [
            1.8,
            0.4,
            0.8
          ],
          "materialKey": "sofa",
          "color": "#D9D1C0"
        },
        {
          "id": "b_table",
          "name": "Outdoor Teak Coffee Table",
          "type": "table",
          "position": [
            1.8,
            0.25,
            5.199999999999999
          ],
          "size": [
            0.9,
            0.35,
            0.6
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        }
      ]
    },
    {
      "id": "master",
      "name": "Presidential Master Suite (Bedroom 1)",
      "category": "MASTER_BEDROOM",
      "floorLevel": 0,
      "dimensions": "19' x 18'",
      "carpetSqft": 308,
      "highlight": "Engineered German Oak Hardwood with walk-in wardrobe and en-suite bath",
      "floorType": "Engineered German Oak Hardwood",
      "floorColor": "#C9A275",
      "wallColor": "#EAE7DF",
      "bounds": {
        "x": -6.9,
        "y": 0.0,
        "z": 0.5,
        "w": 5.8,
        "d": 5.4,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "m_bed",
          "name": "King Bed",
          "type": "bed",
          "position": [
            -6.9,
            0.35,
            0.2
          ],
          "size": [
            2.2,
            0.4,
            2.1
          ],
          "materialKey": "white",
          "color": "#FAFAF6"
        },
        {
          "id": "m_headboard",
          "name": "Acoustic Fluted Headboard",
          "type": "wardrobe",
          "position": [
            -6.9,
            0.95,
            -1.0
          ],
          "size": [
            2.6,
            1.0,
            0.12
          ],
          "materialKey": "wood",
          "color": "#B9824E"
        },
        {
          "id": "m_side_1",
          "name": "Nightstand",
          "type": "table",
          "position": [
            -8.3,
            0.3,
            -0.9
          ],
          "size": [
            0.55,
            0.35,
            0.4
          ],
          "materialKey": "accent",
          "color": "#C9A66B"
        },
        {
          "id": "m_side_2",
          "name": "Nightstand",
          "type": "table",
          "position": [
            -5.5,
            0.3,
            -0.9
          ],
          "size": [
            0.55,
            0.35,
            0.4
          ],
          "materialKey": "accent",
          "color": "#C9A66B"
        }
      ],
      "lights": [
        {
          "position": [
            -6.9,
            2.6,
            0.5
          ],
          "color": "#FFD9A0",
          "intensity": 0.85,
          "distance": 11.0
        }
      ]
    },
    {
      "id": "bedroom_2",
      "name": "Guest Suite (Bedroom 2)",
      "category": "GUEST_BEDROOM",
      "floorLevel": 0,
      "dimensions": "15' x 14'",
      "carpetSqft": 196,
      "highlight": "Matte Vitrified Architectural Tiles (1200x600mm), acoustic double-glazed windows, and built-in wardrobes",
      "floorType": "Matte Vitrified Architectural Tiles (1200x600mm)",
      "floorColor": "#ECE9E2",
      "wallColor": "#F1EEE7",
      "bounds": {
        "x": 6.3,
        "y": 0.0,
        "z": 4.6,
        "w": 4.6,
        "d": 4.4,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "b2_bed",
          "name": "Queen Bed",
          "type": "bed",
          "position": [
            6.3,
            0.35,
            4.4
          ],
          "size": [
            1.9,
            0.4,
            2.0
          ],
          "materialKey": "white",
          "color": "#FAFAF6"
        },
        {
          "id": "b2_side",
          "name": "Bedside Nightstand",
          "type": "table",
          "position": [
            7.6,
            0.3,
            3.4
          ],
          "size": [
            0.5,
            0.35,
            0.4
          ],
          "materialKey": "accent",
          "color": "#C9A66B"
        }
      ]
    }
  ],
  "structuralWalls": [
    {
      "id": "apt_living_balc_seg_0",
      "position": [
        -2.45,
        1.6,
        2.9
      ],
      "size": [
        2.7,
        3.2,
        0.18
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_balc_lintel_0",
      "position": [
        1.8,
        2.85,
        2.9
      ],
      "size": [
        5.8,
        0.7,
        0.18
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_west_seg_0",
      "position": [
        -3.8,
        1.6,
        -1.438
      ],
      "size": [
        0.18,
        3.2,
        2.925
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_west_lintel_0",
      "position": [
        -3.8,
        2.675,
        0.5
      ],
      "size": [
        0.18,
        1.05,
        0.95
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_west_seg_final",
      "position": [
        -3.8,
        1.6,
        1.938
      ],
      "size": [
        0.18,
        3.2,
        1.925
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_east_seg_0",
      "position": [
        3.8,
        1.6,
        -2.35
      ],
      "size": [
        0.18,
        3.2,
        1.1
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_east_lintel_0",
      "position": [
        3.8,
        2.8,
        -0.6
      ],
      "size": [
        0.18,
        0.8,
        2.4
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_east_seg_1",
      "position": [
        3.8,
        1.6,
        1.312
      ],
      "size": [
        0.18,
        3.2,
        1.425
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_east_lintel_1",
      "position": [
        3.8,
        2.675,
        2.5
      ],
      "size": [
        0.18,
        1.05,
        0.95
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_north_seg_0",
      "position": [
        -2.925,
        1.6,
        -2.9
      ],
      "size": [
        1.75,
        3.2,
        0.18
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_north_lintel_0",
      "position": [
        -1.5,
        2.75,
        -2.9
      ],
      "size": [
        1.1,
        0.9,
        0.18
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_living_north_seg_final",
      "position": [
        1.425,
        1.6,
        -2.9
      ],
      "size": [
        4.75,
        3.2,
        0.18
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "apt_master_west_seg_0",
      "position": [
        -9.8,
        1.6,
        -1.5
      ],
      "size": [
        0.22,
        3.2,
        1.4
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "apt_master_west_sill_0",
      "position": [
        -9.8,
        0.425,
        0.5
      ],
      "size": [
        0.22,
        0.85,
        2.6
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "apt_master_west_lintel_0",
      "position": [
        -9.8,
        2.725,
        0.5
      ],
      "size": [
        0.22,
        0.95,
        2.6
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "apt_master_west_seg_final",
      "position": [
        -9.8,
        1.6,
        2.5
      ],
      "size": [
        0.22,
        3.2,
        1.4
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "apt_master_south_seg_0",
      "position": [
        -8.85,
        1.6,
        3.2
      ],
      "size": [
        1.9,
        3.2,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "apt_master_south_sill_0",
      "position": [
        -6.9,
        0.425,
        3.2
      ],
      "size": [
        2.0,
        0.85,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "apt_master_south_lintel_0",
      "position": [
        -6.9,
        2.725,
        3.2
      ],
      "size": [
        2.0,
        0.95,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "apt_master_south_seg_final",
      "position": [
        -4.85,
        1.6,
        3.2
      ],
      "size": [
        2.1,
        3.2,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    }
  ],
  "doors": [
    {
      "id": "slider_apt_living_balc_0",
      "name": "Panoramic Balcony Sliders",
      "position": [
        1.8,
        1.25,
        2.9
      ],
      "size": [
        5.8,
        2.5,
        0.18
      ],
      "rotationY": 0.0,
      "floorLevel": 0,
      "doorType": "sliding",
      "panelsCount": 2,
      "frameMaterial": "dark"
    },
    {
      "id": "door_apt_living_west_0",
      "name": "Master Suite Door",
      "position": [
        -3.8,
        1.075,
        0.5
      ],
      "size": [
        0.95,
        2.15,
        0.18
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 0,
      "doorType": "swing",
      "openAngle": 0.5,
      "frameMaterial": "dark",
      "leafMaterial": "wood2"
    },
    {
      "id": "door_apt_living_east_0",
      "name": "Kitchen Portal Arch",
      "position": [
        3.8,
        1.2,
        -0.6
      ],
      "size": [
        2.4,
        2.4,
        0.18
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 0,
      "doorType": "portal",
      "openAngle": 0.5,
      "frameMaterial": "dark",
      "leafMaterial": "wood2"
    },
    {
      "id": "door_apt_living_east_1",
      "name": "Bedroom 2 Suite Door",
      "position": [
        3.8,
        1.075,
        2.5
      ],
      "size": [
        0.95,
        2.15,
        0.18
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 0,
      "doorType": "swing",
      "openAngle": 0.5,
      "frameMaterial": "dark",
      "leafMaterial": "wood2"
    },
    {
      "id": "door_apt_living_north_0",
      "name": "Main Entrance Door",
      "position": [
        -1.5,
        1.15,
        -2.9
      ],
      "size": [
        1.1,
        2.3,
        0.18
      ],
      "rotationY": 0.0,
      "floorLevel": 0,
      "doorType": "pivot",
      "openAngle": 0.5,
      "frameMaterial": "dark",
      "leafMaterial": "wood2"
    }
  ],
  "windows": [
    {
      "id": "win_apt_master_west_0",
      "name": "Master Suite Horizon Window",
      "position": [
        -9.8,
        1.55,
        0.5
      ],
      "size": [
        2.6,
        1.4
      ],
      "rotationY": 1.5707963267948966,
      "sillHeight": 0.85,
      "floorLevel": 0,
      "hasMullions": true,
      "frameMaterial": "dark"
    },
    {
      "id": "win_apt_master_south_0",
      "name": "Master Suite Sunset Window",
      "position": [
        -6.9,
        1.55,
        3.2
      ],
      "size": [
        2.0,
        1.4
      ],
      "rotationY": 0.0,
      "sillHeight": 0.85,
      "floorLevel": 0,
      "hasMullions": true,
      "frameMaterial": "dark"
    }
  ],
  "balconies": [
    {
      "id": "balc_sky_deck_apt",
      "name": "Covered Sky Balcony & Deck",
      "floorLevel": 0,
      "bounds": {
        "x": 1.8,
        "y": 0.0,
        "z": 4.6,
        "w": 5.3,
        "d": 3.4,
        "h": 0.2
      },
      "deckMaterial": "deck",
      "railings": [
        {
          "id": "balc_sky_deck_apt_rail_front",
          "position": [
            1.8,
            0.55,
            6.3
          ],
          "size": [
            5.3,
            1.1
          ],
          "rotationY": 0.0,
          "type": "glass_balustrade",
          "handrail": true
        },
        {
          "id": "balc_sky_deck_apt_rail_left",
          "position": [
            -0.85,
            0.55,
            4.6
          ],
          "size": [
            3.4,
            1.1
          ],
          "rotationY": 1.5707963267948966,
          "type": "glass_balustrade",
          "handrail": true
        },
        {
          "id": "balc_sky_deck_apt_rail_right",
          "position": [
            4.45,
            0.55,
            4.6
          ],
          "size": [
            3.4,
            1.1
          ],
          "rotationY": 1.5707963267948966,
          "type": "glass_balustrade",
          "handrail": true
        }
      ]
    }
  ],
  "glassPanels": [
    {
      "id": "balc_sky_deck_apt_rail_front",
      "position": [
        1.8,
        0.55,
        6.3
      ],
      "size": [
        5.3,
        1.1
      ],
      "rotationY": 0.0,
      "floorLevel": 0,
      "handrail": true
    },
    {
      "id": "balc_sky_deck_apt_rail_left",
      "position": [
        -0.85,
        0.55,
        4.6
      ],
      "size": [
        3.4,
        1.1
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 0,
      "handrail": true
    },
    {
      "id": "balc_sky_deck_apt_rail_right",
      "position": [
        4.45,
        0.55,
        4.6
      ],
      "size": [
        3.4,
        1.1
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 0,
      "handrail": true
    }
  ],
  "focalTargets": {
    "living": {
      "target": [
        -0.8,
        1.6,
        0.8
      ],
      "theta": 0.45,
      "phi": 1.05,
      "radius": 14.0,
      "walk": [
        -1.0,
        1.65,
        3.2
      ]
    },
    "kitchen": {
      "target": [
        5.8,
        1.5,
        -0.6
      ],
      "theta": 1.95,
      "phi": 1.05,
      "radius": 12.5,
      "walk": [
        4.699999999999999,
        1.65,
        1.2
      ]
    },
    "balcony": {
      "target": [
        1.8,
        1.2,
        4.6
      ],
      "theta": 2.35,
      "phi": 1.05,
      "radius": 12.0,
      "walk": [
        0.8,
        1.65,
        3.8
      ]
    },
    "master": {
      "target": [
        -6.9,
        1.5,
        0.5
      ],
      "theta": 0.35,
      "phi": 1.08,
      "radius": 13.0,
      "walk": [
        -5.5,
        1.65,
        2.2
      ]
    },
    "bedroom_2": {
      "target": [
        6.3,
        1.5,
        4.6
      ],
      "theta": 1.85,
      "phi": 1.08,
      "radius": 12.0,
      "walk": [
        4.9,
        1.65,
        3.6
      ]
    },
    "all": {
      "target": [
        0.0,
        2.8,
        0.0
      ],
      "theta": 0.72,
      "phi": 1.05,
      "radius": 34.0,
      "walk": [
        0.0,
        1.65,
        12.0
      ]
    }
  },
  "waypoints": [
    {
      "p": [
        4.0,
        3.5,
        18.0
      ],
      "l": [
        0.0,
        2.5,
        0.0
      ],
      "label": "Approach · Blue Waves Residence"
    },
    {
      "p": [
        -1.0,
        1.65,
        3.2
      ],
      "l": [
        2.0,
        1.2,
        0.0
      ],
      "label": "Living & Dining Pavilion (24' x 19')"
    },
    {
      "p": [
        4.699999999999999,
        1.65,
        1.2
      ],
      "l": [
        6.8,
        1.1,
        -1.0
      ],
      "label": "Culinary Kitchen Studio (3.09:1 Hall Ratio)"
    },
    {
      "p": [
        0.8,
        1.65,
        3.8
      ],
      "l": [
        2.8,
        1.4,
        5.8
      ],
      "label": "Covered Sky Deck & Balcony"
    },
    {
      "p": [
        -5.5,
        1.65,
        2.2
      ],
      "l": [
        -7.9,
        1.1,
        -0.6
      ],
      "label": "Presidential Master Suite (Bedroom 1)"
    },
    {
      "p": [
        4.9,
        1.65,
        3.6
      ],
      "l": [
        7.2,
        1.1,
        4.8
      ],
      "label": "Guest Suite (Bedroom 2)"
    },
    {
      "p": [
        18.0,
        16.0,
        18.0
      ],
      "l": [
        0.0,
        3.0,
        0.0
      ],
      "label": "Aerial · Full 3D Spatial Digital Twin"
    }
  ],
  "fixtures": [
    {
      "item": "2 Distinct Bedroom Suites",
      "detail": "Accurately mapped with Master Suite + 1 secondary suites",
      "included": true
    },
    {
      "item": "Calibrated 3:1 Living Hall to Kitchen Ratio",
      "detail": "Grand entertainment volume with dedicated ergonomic culinary studio",
      "included": true
    },
    {
      "item": "Structural BIM Perimeter & Partition Walls",
      "detail": "Full height architectural walls with proper openings and skirting",
      "included": true
    },
    {
      "item": "Matte Vitrified Architectural Tiles (1200x600mm) Flooring",
      "detail": "Authentic finish matching database schema (VITRIFIED_TILES)",
      "included": true
    },
    {
      "item": "Fully Furnished Interior State",
      "detail": "Interior objects moulded directly to FULLY_FURNISHED status",
      "included": true
    },
    {
      "item": "East Sunlight Alignment",
      "detail": "Directional sun and ambient temperature calibrated to EAST",
      "included": true
    },
    {
      "item": "Teak Balconies with Safety Glass Balustrades",
      "detail": "1 bounded exterior balcony systems placed",
      "included": true
    }
  ]
};

export default TEST_APT_2BHK_BLUEPRINT;
