// AUTO-GENERATED BY SOVEREIGN DIGITAL TWIN COMPILER (PRISMA SCHEMA CONFORMANT)
// Target Component: digital_twin/DynamicThreeTwinViewer.tsx
// Property: Golfshire Fairway Presidential Villa (test-villa-4bhk)

export interface SpatialBox {
  x: number;
  y: number;
  z: number;
  w: number;
  d: number;
  h: number;
}

export interface StagedFurniture {
  id: string;
  name: string;
  type: string;
  position: [number, number, number];
  size: [number, number, number];
  materialKey: string;
  color?: string;
  rotationY?: number;
}

export interface InspectionDefectPin {
  id: string;
  roomId: string;
  roomName: string;
  type: string;
  severity: string;
  position: [number, number, number];
  color: string;
  description: string;
  floorLevel: number;
}

export interface DigitalTwinRoom {
  id: string;
  name: string;
  category?: string;
  dimensions: string;
  carpetSqft: number;
  highlight: string;
  floorType: string;
  floorColor: string;
  wallColor: string;
  floorLevel?: number;
  bounds: SpatialBox;
  furniture: StagedFurniture[];
  lights?: Array<{ position: [number, number, number]; color: string; intensity: number; distance: number }>;
  defects?: InspectionDefectPin[];
}

export interface StructuralWall {
  id: string;
  position: [number, number, number];
  size: [number, number, number];
  materialKey: string;
  isExterior?: boolean;
  floorLevel?: number;
}

export interface DoorSpecification {
  id: string;
  name: string;
  position: [number, number, number];
  size: [number, number, number];
  rotationY: number;
  floorLevel: number;
  doorType: string;
  openAngle?: number;
  panelsCount?: number;
  frameMaterial: string;
  leafMaterial?: string;
}

export interface WindowSpecification {
  id: string;
  name: string;
  position: [number, number, number];
  size: [number, number];
  rotationY: number;
  sillHeight: number;
  floorLevel: number;
  hasMullions: boolean;
  frameMaterial: string;
}

export interface BalconySpecification {
  id: string;
  name: string;
  floorLevel: number;
  bounds: SpatialBox;
  deckMaterial: string;
  railings: Array<{
    id: string;
    position: [number, number, number];
    size: [number, number];
    rotationY: number;
    type: string;
    handrail?: boolean;
  }>;
}

export interface GlassPanel {
  id: string;
  position: [number, number, number];
  size: [number, number];
  rotationY?: number;
  floorLevel?: number;
  handrail?: boolean;
}

export interface CameraFocalTarget {
  target: [number, number, number];
  theta: number;
  phi: number;
  radius: number;
  walk: [number, number, number];
}

export interface TourWaypoint {
  p: [number, number, number];
  l: [number, number, number];
  label: string;
}

export interface FloorLevelSpec {
  id: string;
  name: string;
  elevation: number;
  roomIds: string[];
}

export interface DigitalTwinBlueprint {
  propertyId: string;
  publicId?: string;
  propertyTitle: string;
  locality?: string;
  city: string;
  state: string;
  propertyType?: string;
  configuration?: string;
  bhkCount?: number;
  conditionScore: number;
  carpetSqft: number;
  builtUpSqft: number;
  floor?: string;
  floorHeight: string;
  flooring?: string;
  furnishing?: string;
  facing?: string;
  views?: string[];
  balconyCount?: number;
  bathroomsCount?: number;
  efficiency: number;
  orientation: string;
  archetype?: string;
  levelsCount?: number;
  aboutSummary?: string;
  environmentalTheme: string;
  sunlightDirection?: [number, number, number];
  sunlightColor?: string;
  defects?: InspectionDefectPin[];
  floors?: FloorLevelSpec[];
  rooms: DigitalTwinRoom[];
  structuralWalls: StructuralWall[];
  doors?: DoorSpecification[];
  windows?: WindowSpecification[];
  balconies?: BalconySpecification[];
  glassPanels: GlassPanel[];
  focalTargets: Record<string, CameraFocalTarget>;
  waypoints: TourWaypoint[];
  fixtures: Array<{ item: string; detail: string; included: boolean }>;
}

export const TEST_VILLA_4BHK_BLUEPRINT: DigitalTwinBlueprint = {
  "propertyId": "test-villa-4bhk",
  "publicId": "prop_test-villa-4",
  "propertyTitle": "Golfshire Fairway Presidential Villa",
  "locality": "Prime Corridor",
  "city": "Mumbai",
  "state": "Maharashtra",
  "propertyType": "VILLA",
  "configuration": "4 BHK",
  "bhkCount": 4,
  "carpetSqft": 4200,
  "builtUpSqft": 5376,
  "floor": "G + 2 Villa (3 Floors)",
  "floorHeight": "11.0 ft (Double Height Void: 22 ft)",
  "flooring": "ITALIAN_MARBLE",
  "furnishing": "FULLY_FURNISHED",
  "facing": "EAST",
  "views": [
    "POOL",
    "GOLF_COURSE"
  ],
  "balconyCount": 3,
  "bathroomsCount": 4,
  "conditionScore": 9.6,
  "efficiency": 84,
  "orientation": "East-Facing",
  "archetype": "villa_g2",
  "levelsCount": 3,
  "environmentalTheme": "pune_hills",
  "sunlightDirection": [
    18.0,
    14.0,
    16.0
  ],
  "sunlightColor": "#FFF2DE",
  "aboutSummary": "DB Digital Twin: 'Golfshire Fairway Presidential Villa'. Schema: VILLA (4 BHK), 4,200 sq.ft on G + 2 Villa (3 Floors). Flooring: Italian Statuario & Botticino Marble. Furnishing: FULLY_FURNISHED. Facing: EAST. Views: POOL, GOLF_COURSE. BIM layout strictly allocates 4 bedrooms with calibrated 3:1 hall-to-kitchen ratio. Civil inspection audit: Clean structure (9.6/10).",
  "defects": [],
  "floors": [
    {
      "id": "floor_0",
      "name": "Ground Floor (Grand Living & Pool Deck)",
      "elevation": 0.0,
      "roomIds": [
        "living",
        "kitchen",
        "pool_deck",
        "foyer"
      ]
    },
    {
      "id": "floor_1",
      "name": "First Floor (Master Suite & Mezzanine)",
      "elevation": 3.7,
      "roomIds": [
        "master",
        "mezzanine",
        "bedroom_2"
      ]
    },
    {
      "id": "floor_2",
      "name": "Second Floor (Bedrooms 3 & 4 & Sky Deck)",
      "elevation": 7.4,
      "roomIds": [
        "bedroom_3",
        "bedroom_4",
        "sky_terrace"
      ]
    }
  ],
  "rooms": [
    {
      "id": "living",
      "name": "Double-Height Grand Living & Dining Hall",
      "category": "LIVING_ROOM",
      "floorLevel": 0,
      "dimensions": "32' x 24' (22ft Ceiling)",
      "carpetSqft": 1428,
      "highlight": "22ft double-height ceiling with Italian Statuario & Botticino Marble and floor-to-ceiling glass opening to pool deck",
      "floorType": "Italian Statuario & Botticino Marble",
      "floorColor": "#F4F1EA",
      "wallColor": "#FAF8F5",
      "bounds": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0,
        "w": 10.0,
        "d": 7.5,
        "h": 6.4
      },
      "furniture": [
        {
          "id": "sofa_main",
          "name": "Sectional White Boucle Sofa",
          "type": "sofa",
          "position": [
            -1.2,
            0.45,
            1.8
          ],
          "size": [
            4.5,
            0.85,
            2.0
          ],
          "materialKey": "sofa",
          "color": "#D9D1C0"
        },
        {
          "id": "coffee_tbl",
          "name": "Low Marble Coffee Table",
          "type": "table",
          "position": [
            -1.2,
            0.25,
            0.2
          ],
          "size": [
            2.4,
            0.45,
            1.2
          ],
          "materialKey": "white",
          "color": "#FAFAF6"
        },
        {
          "id": "living_rug",
          "name": "Textured Hand-Woven Rug",
          "type": "rug",
          "position": [
            -1.2,
            0.02,
            1.0
          ],
          "size": [
            5.6,
            0.02,
            4.0
          ],
          "materialKey": "rug",
          "color": "#CABFA8"
        },
        {
          "id": "dining_tbl",
          "name": "8-Seater Smoked Oak Dining Table",
          "type": "table",
          "position": [
            2.5,
            0.45,
            -1.0
          ],
          "size": [
            2.8,
            0.85,
            1.4
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        },
        {
          "id": "tv_console",
          "name": "Fluted Marble Media Console",
          "type": "tv_unit",
          "position": [
            -1.2,
            0.35,
            -3.2
          ],
          "size": [
            3.6,
            0.6,
            0.5
          ],
          "materialKey": "dark",
          "color": "#3A3A40"
        }
      ],
      "lights": [
        {
          "position": [
            -1.2,
            5.2,
            0.5
          ],
          "color": "#FFD9A0",
          "intensity": 1.2,
          "distance": 16.0
        }
      ]
    },
    {
      "id": "kitchen",
      "name": "Siemens Integrated Gourmet Kitchen",
      "category": "KITCHEN",
      "floorLevel": 0,
      "dimensions": "16' x 16'",
      "carpetSqft": 462,
      "highlight": "Central culinary island, integrated induction downdraft & soft-close Blum joinery",
      "floorType": "Honed Nero Impala Granite & Quartzite",
      "floorColor": "#263238",
      "wallColor": "#FAF8F5",
      "bounds": {
        "x": 7.6,
        "y": 0.0,
        "z": 0.0,
        "w": 4.8,
        "d": 4.8,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "k_island",
          "name": "Corian Central Island with Wine Chiller",
          "type": "counter",
          "position": [
            7.6,
            0.5,
            0.0
          ],
          "size": [
            3.2,
            0.95,
            1.4
          ],
          "materialKey": "counter",
          "color": "#8D6F50"
        },
        {
          "id": "k_stools",
          "name": "Bar Stools Set",
          "type": "stool",
          "position": [
            7.6,
            0.4,
            -1.1
          ],
          "size": [
            2.4,
            0.75,
            0.45
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        }
      ],
      "lights": [
        {
          "position": [
            7.6,
            2.8,
            0.0
          ],
          "color": "#FFFFFF",
          "intensity": 0.9,
          "distance": 11.0
        }
      ]
    },
    {
      "id": "pool_deck",
      "name": "Heated Infinity Pool Deck",
      "category": "BALCONY",
      "floorLevel": 0,
      "dimensions": "30' x 16'",
      "carpetSqft": 504,
      "highlight": "Weatherproof teak deck with Balinese stone heated plunge pool and glass balustrades",
      "floorType": "Weatherproof Teak Composite Deck",
      "floorColor": "#A87042",
      "wallColor": "#FAF8F5",
      "bounds": {
        "x": 0.0,
        "y": 0.0,
        "z": 8.0,
        "w": 9.0,
        "d": 5.0,
        "h": 1.2
      },
      "furniture": [
        {
          "id": "pool_water",
          "name": "Heated Infinity Plunge Pool",
          "type": "counter",
          "position": [
            0.0,
            0.35,
            8.5
          ],
          "size": [
            6.0,
            0.45,
            2.8
          ],
          "materialKey": "pool",
          "color": "#0F2B36"
        },
        {
          "id": "lounger_1",
          "name": "Balinese Teak Sun Lounger",
          "type": "chair",
          "position": [
            -3.2,
            0.35,
            7.2
          ],
          "size": [
            1.8,
            0.4,
            0.8
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        },
        {
          "id": "lounger_2",
          "name": "Balinese Teak Sun Lounger",
          "type": "chair",
          "position": [
            3.2,
            0.35,
            7.2
          ],
          "size": [
            1.8,
            0.4,
            0.8
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        }
      ]
    },
    {
      "id": "master",
      "name": "Presidential Master Suite (Bedroom 1 - 1st Floor)",
      "category": "MASTER_BEDROOM",
      "floorLevel": 1,
      "dimensions": "21' x 19'",
      "carpetSqft": 924,
      "highlight": "Engineered German Oak Hardwood with walk-in dressing wardrobe and private balcony",
      "floorType": "Engineered German Oak Hardwood",
      "floorColor": "#C9A275",
      "wallColor": "#EAE7DF",
      "bounds": {
        "x": -6.5,
        "y": 3.7,
        "z": 0.5,
        "w": 6.4,
        "d": 5.8,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "m_bed",
          "name": "King Master Bed",
          "type": "bed",
          "position": [
            -6.5,
            4.15,
            0.2
          ],
          "size": [
            2.2,
            0.5,
            2.2
          ],
          "materialKey": "white",
          "color": "#FAFAF6"
        },
        {
          "id": "m_wardrobe",
          "name": "Walk-in Dressing Wardrobe",
          "type": "wardrobe",
          "position": [
            -6.5,
            4.8,
            -2.0
          ],
          "size": [
            3.6,
            2.2,
            0.6
          ],
          "materialKey": "wood2",
          "color": "#8D6F50"
        },
        {
          "id": "m_side1",
          "name": "Floating Nightstand",
          "type": "table",
          "position": [
            -8.0,
            4.0,
            0.2
          ],
          "size": [
            0.6,
            0.4,
            0.4
          ],
          "materialKey": "accent",
          "color": "#C9A66B"
        },
        {
          "id": "m_side2",
          "name": "Floating Nightstand",
          "type": "table",
          "position": [
            -5.0,
            4.0,
            0.2
          ],
          "size": [
            0.6,
            0.4,
            0.4
          ],
          "materialKey": "accent",
          "color": "#C9A66B"
        }
      ],
      "lights": [
        {
          "position": [
            -6.5,
            6.2,
            0.5
          ],
          "color": "#FFD9A0",
          "intensity": 0.9,
          "distance": 12.0
        }
      ]
    },
    {
      "id": "mezzanine",
      "name": "Mezzanine Overlook Bridge & Gallery",
      "category": "LIVING_ROOM",
      "floorLevel": 1,
      "dimensions": "20' x 11'",
      "carpetSqft": 336,
      "highlight": "Glass-railed architectural bridge suspended over double-height grand living hall",
      "floorType": "Engineered German Oak Hardwood",
      "floorColor": "#C9A275",
      "wallColor": "#EAE7DF",
      "bounds": {
        "x": 0.0,
        "y": 3.7,
        "z": -1.8,
        "w": 6.0,
        "d": 3.4,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "mezz_lounger",
          "name": "Mezzanine Reading Daybed",
          "type": "sofa",
          "position": [
            0.0,
            4.15,
            -2.0
          ],
          "size": [
            2.2,
            0.6,
            1.0
          ],
          "materialKey": "sofa",
          "color": "#D9D1C0"
        }
      ]
    },
    {
      "id": "bedroom_2",
      "name": "Junior Master Suite (Bedroom 2 - 1st Floor)",
      "category": "GUEST_BEDROOM",
      "floorLevel": 1,
      "dimensions": "18' x 16'",
      "carpetSqft": 588,
      "highlight": "Engineered German Oak Hardwood with ensuite bath and morning sun balcony",
      "floorType": "Engineered German Oak Hardwood",
      "floorColor": "#C9A275",
      "wallColor": "#EAE7DF",
      "bounds": {
        "x": 6.8,
        "y": 3.7,
        "z": 0.5,
        "w": 5.4,
        "d": 5.0,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "b2_bed",
          "name": "Queen Bed",
          "type": "bed",
          "position": [
            6.8,
            4.15,
            0.0
          ],
          "size": [
            1.9,
            0.5,
            2.0
          ],
          "materialKey": "white",
          "color": "#FAFAF6"
        },
        {
          "id": "b2_desk",
          "name": "Study Writing Desk",
          "type": "table",
          "position": [
            8.5,
            4.1,
            1.5
          ],
          "size": [
            1.4,
            0.75,
            0.6
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        }
      ]
    },
    {
      "id": "bedroom_3",
      "name": "Sky Villa Suite (Bedroom 3 - 2nd Floor)",
      "category": "GUEST_BEDROOM",
      "floorLevel": 2,
      "dimensions": "16' x 15'",
      "carpetSqft": 504,
      "highlight": "Panoramic upper-level bedroom with direct access to rooftop sky pergola deck",
      "floorType": "Italian Statuario & Botticino Marble",
      "floorColor": "#F4F1EA",
      "wallColor": "#FAF8F5",
      "bounds": {
        "x": -5.0,
        "y": 7.4,
        "z": -0.5,
        "w": 5.0,
        "d": 4.8,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "b3_bed",
          "name": "Queen Bed",
          "type": "bed",
          "position": [
            -5.0,
            7.85,
            -0.5
          ],
          "size": [
            1.9,
            0.5,
            2.0
          ],
          "materialKey": "white",
          "color": "#FAFAF6"
        },
        {
          "id": "b3_side",
          "name": "Nightstand",
          "type": "table",
          "position": [
            -6.4,
            7.7,
            -0.5
          ],
          "size": [
            0.5,
            0.4,
            0.4
          ],
          "materialKey": "accent",
          "color": "#C9A66B"
        }
      ]
    },
    {
      "id": "bedroom_4",
      "name": "Penthouse Suite (Bedroom 4 - 2nd Floor)",
      "category": "GUEST_BEDROOM",
      "floorLevel": 2,
      "dimensions": "16' x 15'",
      "carpetSqft": 504,
      "highlight": "Dual-aspect horizon bedroom suite with panoramic private terrace views",
      "floorType": "Italian Statuario & Botticino Marble",
      "floorColor": "#F4F1EA",
      "wallColor": "#FAF8F5",
      "bounds": {
        "x": 5.0,
        "y": 7.4,
        "z": -0.5,
        "w": 5.0,
        "d": 4.8,
        "h": 3.2
      },
      "furniture": [
        {
          "id": "b4_bed",
          "name": "Queen Bed",
          "type": "bed",
          "position": [
            5.0,
            7.85,
            -0.5
          ],
          "size": [
            1.9,
            0.5,
            2.0
          ],
          "materialKey": "white",
          "color": "#FAFAF6"
        },
        {
          "id": "b4_desk",
          "name": "Executive Study Desk",
          "type": "table",
          "position": [
            6.5,
            7.85,
            0.8
          ],
          "size": [
            1.4,
            0.75,
            0.6
          ],
          "materialKey": "wood2",
          "color": "#A87042"
        }
      ]
    },
    {
      "id": "sky_terrace",
      "name": "Rooftop Sky Pergola Deck",
      "category": "BALCONY",
      "floorLevel": 2,
      "dimensions": "28' x 15'",
      "carpetSqft": 420,
      "highlight": "Teak deck with 360-degree horizon panorama, glass balustrades & champagne gold top rail",
      "floorType": "Weatherproof Teak Composite Deck",
      "floorColor": "#A87042",
      "wallColor": "#FAF8F5",
      "bounds": {
        "x": 0.0,
        "y": 7.4,
        "z": 4.5,
        "w": 8.4,
        "d": 4.6,
        "h": 1.1
      },
      "furniture": [
        {
          "id": "sky_sofa",
          "name": "All-Weather Modular Sky Lounge",
          "type": "chair",
          "position": [
            0.0,
            7.8,
            4.5
          ],
          "size": [
            2.6,
            0.6,
            1.2
          ],
          "materialKey": "sofa",
          "color": "#D9D1C0"
        }
      ]
    }
  ],
  "structuralWalls": [
    {
      "id": "v_l0_south_seg_0",
      "position": [
        -4.0,
        3.2,
        3.8
      ],
      "size": [
        2.0,
        6.4,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_south_lintel_0",
      "position": [
        0.0,
        4.7,
        3.8
      ],
      "size": [
        6.0,
        3.4,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_south_seg_final",
      "position": [
        4.0,
        3.2,
        3.8
      ],
      "size": [
        2.0,
        6.4,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_west_seg_0",
      "position": [
        -5.0,
        3.2,
        -2.65
      ],
      "size": [
        0.22,
        6.4,
        2.3
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_west_sill_0",
      "position": [
        -5.0,
        0.3,
        0.0
      ],
      "size": [
        0.22,
        0.6,
        3.0
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_west_lintel_0",
      "position": [
        -5.0,
        5.1,
        0.0
      ],
      "size": [
        0.22,
        2.6,
        3.0
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_west_seg_final",
      "position": [
        -5.0,
        3.2,
        2.65
      ],
      "size": [
        0.22,
        6.4,
        2.3
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_east_part_seg_0",
      "position": [
        5.0,
        1.6,
        -2.55
      ],
      "size": [
        0.18,
        3.2,
        2.5
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "v_l0_east_part_lintel_0",
      "position": [
        5.0,
        2.9,
        0.0
      ],
      "size": [
        0.18,
        0.6,
        2.6
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "v_l0_east_part_seg_final",
      "position": [
        5.0,
        1.6,
        2.55
      ],
      "size": [
        0.18,
        3.2,
        2.5
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 0
    },
    {
      "id": "v_l0_north_seg_0",
      "position": [
        -2.8,
        3.2,
        -3.8
      ],
      "size": [
        4.4,
        6.4,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_north_lintel_0",
      "position": [
        0.0,
        4.4,
        -3.8
      ],
      "size": [
        1.2,
        4.0,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_north_seg_final",
      "position": [
        2.8,
        3.2,
        -3.8
      ],
      "size": [
        4.4,
        6.4,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_kit_south_seg_0",
      "position": [
        5.7,
        1.6,
        2.4
      ],
      "size": [
        1.4,
        3.2,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_kit_south_sill_0",
      "position": [
        7.5,
        0.55,
        2.4
      ],
      "size": [
        2.2,
        1.1,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_kit_south_lintel_0",
      "position": [
        7.5,
        2.75,
        2.4
      ],
      "size": [
        2.2,
        0.9,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_kit_south_seg_final",
      "position": [
        9.3,
        1.6,
        2.4
      ],
      "size": [
        1.4,
        3.2,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_kit_east_seg_0",
      "position": [
        10.0,
        1.6,
        -1.7
      ],
      "size": [
        0.22,
        3.2,
        1.4
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_kit_east_sill_0",
      "position": [
        10.0,
        0.55,
        0.0
      ],
      "size": [
        0.22,
        1.1,
        2.0
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_kit_east_lintel_0",
      "position": [
        10.0,
        2.75,
        0.0
      ],
      "size": [
        0.22,
        0.9,
        2.0
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l0_kit_east_seg_final",
      "position": [
        10.0,
        1.6,
        1.7
      ],
      "size": [
        0.22,
        3.2,
        1.4
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 0
    },
    {
      "id": "v_l1_m_east_seg_0",
      "position": [
        -3.1,
        5.3,
        -1.2
      ],
      "size": [
        0.18,
        3.2,
        2.4
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_east_lintel_0",
      "position": [
        -3.1,
        6.4,
        0.5
      ],
      "size": [
        0.18,
        1.0,
        1.0
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_east_seg_final",
      "position": [
        -3.1,
        5.3,
        2.2
      ],
      "size": [
        0.18,
        3.2,
        2.4
      ],
      "materialKey": "cream",
      "isExterior": false,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_west_seg_0",
      "position": [
        -9.9,
        5.3,
        -1.6
      ],
      "size": [
        0.22,
        3.2,
        1.6
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_west_sill_0",
      "position": [
        -9.9,
        4.125,
        0.5
      ],
      "size": [
        0.22,
        0.85,
        2.6
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_west_lintel_0",
      "position": [
        -9.9,
        6.475,
        0.5
      ],
      "size": [
        0.22,
        0.85,
        2.6
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_west_seg_final",
      "position": [
        -9.9,
        5.3,
        2.6
      ],
      "size": [
        0.22,
        3.2,
        1.6
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_south_seg_0",
      "position": [
        -8.8,
        5.3,
        3.4
      ],
      "size": [
        2.2,
        3.2,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_south_lintel_0",
      "position": [
        -6.5,
        6.5,
        3.4
      ],
      "size": [
        2.4,
        0.8,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 1
    },
    {
      "id": "v_l1_m_south_seg_final",
      "position": [
        -4.2,
        5.3,
        3.4
      ],
      "size": [
        2.2,
        3.2,
        0.22
      ],
      "materialKey": "cream2",
      "isExterior": true,
      "floorLevel": 1
    }
  ],
  "doors": [
    {
      "id": "slider_v_l0_south_0",
      "name": "Grand Fairway Sliders",
      "position": [
        0.0,
        1.5,
        3.8
      ],
      "size": [
        6.0,
        3.0,
        0.22
      ],
      "rotationY": 0.0,
      "floorLevel": 0,
      "doorType": "sliding",
      "panelsCount": 2,
      "frameMaterial": "dark"
    },
    {
      "id": "door_v_l0_east_part_0",
      "name": "Kitchen Grand Archway",
      "position": [
        5.0,
        1.3,
        0.0
      ],
      "size": [
        2.6,
        2.6,
        0.18
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 0,
      "doorType": "portal",
      "openAngle": 0.5,
      "frameMaterial": "dark",
      "leafMaterial": "wood2"
    },
    {
      "id": "door_v_l0_north_0",
      "name": "Grand Entrance Pivot Door",
      "position": [
        0.0,
        1.2,
        -3.8
      ],
      "size": [
        1.2,
        2.4,
        0.22
      ],
      "rotationY": 0.0,
      "floorLevel": 0,
      "doorType": "pivot",
      "openAngle": 0.5,
      "frameMaterial": "dark",
      "leafMaterial": "wood2"
    },
    {
      "id": "door_v_l1_m_east_0",
      "name": "Presidential Suite Door",
      "position": [
        -3.1,
        4.8,
        0.5
      ],
      "size": [
        1.0,
        2.2,
        0.18
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 1,
      "doorType": "swing",
      "openAngle": 0.5,
      "frameMaterial": "dark",
      "leafMaterial": "wood2"
    },
    {
      "id": "slider_v_l1_m_south_0",
      "name": "Master Balcony Slider",
      "position": [
        -6.5,
        4.9,
        3.4
      ],
      "size": [
        2.4,
        2.4,
        0.22
      ],
      "rotationY": 0.0,
      "floorLevel": 1,
      "doorType": "sliding",
      "panelsCount": 2,
      "frameMaterial": "dark"
    }
  ],
  "windows": [
    {
      "id": "win_v_l0_west_0",
      "name": "Double Height West Window",
      "position": [
        -5.0,
        2.2,
        0.0
      ],
      "size": [
        3.0,
        3.2
      ],
      "rotationY": 1.5707963267948966,
      "sillHeight": 0.6,
      "floorLevel": 0,
      "hasMullions": true,
      "frameMaterial": "dark"
    },
    {
      "id": "win_v_l0_kit_south_0",
      "name": "Kitchen Garden Window",
      "position": [
        7.5,
        1.7,
        2.4
      ],
      "size": [
        2.2,
        1.2
      ],
      "rotationY": 0.0,
      "sillHeight": 1.1,
      "floorLevel": 0,
      "hasMullions": true,
      "frameMaterial": "dark"
    },
    {
      "id": "win_v_l0_kit_east_0",
      "name": "Kitchen East Window",
      "position": [
        10.0,
        1.7,
        0.0
      ],
      "size": [
        2.0,
        1.2
      ],
      "rotationY": 1.5707963267948966,
      "sillHeight": 1.1,
      "floorLevel": 0,
      "hasMullions": true,
      "frameMaterial": "dark"
    },
    {
      "id": "win_v_l1_m_west_0",
      "name": "Master Horizon Window",
      "position": [
        -9.9,
        5.3,
        0.5
      ],
      "size": [
        2.6,
        1.5
      ],
      "rotationY": 1.5707963267948966,
      "sillHeight": 0.85,
      "floorLevel": 1,
      "hasMullions": true,
      "frameMaterial": "dark"
    }
  ],
  "balconies": [
    {
      "id": "balc_master_v1",
      "name": "Master Fairway Balcony",
      "floorLevel": 1,
      "bounds": {
        "x": -6.5,
        "y": 3.7,
        "z": 4.5,
        "w": 4.2,
        "d": 2.0,
        "h": 0.2
      },
      "deckMaterial": "deck",
      "railings": [
        {
          "id": "balc_master_v1_rail_front",
          "position": [
            -6.5,
            4.25,
            5.5
          ],
          "size": [
            4.2,
            1.1
          ],
          "rotationY": 0.0,
          "type": "glass_balustrade",
          "handrail": true
        },
        {
          "id": "balc_master_v1_rail_left",
          "position": [
            -8.6,
            4.25,
            4.5
          ],
          "size": [
            2.0,
            1.1
          ],
          "rotationY": 1.5707963267948966,
          "type": "glass_balustrade",
          "handrail": true
        },
        {
          "id": "balc_master_v1_rail_right",
          "position": [
            -4.4,
            4.25,
            4.5
          ],
          "size": [
            2.0,
            1.1
          ],
          "rotationY": 1.5707963267948966,
          "type": "glass_balustrade",
          "handrail": true
        }
      ]
    },
    {
      "id": "balc_sky_terrace_v2",
      "name": "Rooftop Sky Pergola Deck",
      "floorLevel": 2,
      "bounds": {
        "x": 0.0,
        "y": 7.4,
        "z": 4.5,
        "w": 8.4,
        "d": 4.6,
        "h": 0.2
      },
      "deckMaterial": "deck",
      "railings": [
        {
          "id": "balc_sky_terrace_v2_rail_front",
          "position": [
            0.0,
            7.95,
            6.8
          ],
          "size": [
            8.4,
            1.1
          ],
          "rotationY": 0.0,
          "type": "glass_balustrade",
          "handrail": true
        },
        {
          "id": "balc_sky_terrace_v2_rail_left",
          "position": [
            -4.2,
            7.95,
            4.5
          ],
          "size": [
            4.6,
            1.1
          ],
          "rotationY": 1.5707963267948966,
          "type": "glass_balustrade",
          "handrail": true
        },
        {
          "id": "balc_sky_terrace_v2_rail_right",
          "position": [
            4.2,
            7.95,
            4.5
          ],
          "size": [
            4.6,
            1.1
          ],
          "rotationY": 1.5707963267948966,
          "type": "glass_balustrade",
          "handrail": true
        }
      ]
    }
  ],
  "glassPanels": [
    {
      "id": "balc_master_v1_rail_front",
      "position": [
        -6.5,
        4.25,
        5.5
      ],
      "size": [
        4.2,
        1.1
      ],
      "rotationY": 0.0,
      "floorLevel": 1,
      "handrail": true
    },
    {
      "id": "balc_master_v1_rail_left",
      "position": [
        -8.6,
        4.25,
        4.5
      ],
      "size": [
        2.0,
        1.1
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 1,
      "handrail": true
    },
    {
      "id": "balc_master_v1_rail_right",
      "position": [
        -4.4,
        4.25,
        4.5
      ],
      "size": [
        2.0,
        1.1
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 1,
      "handrail": true
    },
    {
      "id": "mezzanine_rail",
      "position": [
        0.0,
        4.25,
        -0.3
      ],
      "size": [
        6.0,
        1.1
      ],
      "rotationY": 0.0,
      "floorLevel": 1,
      "handrail": true
    },
    {
      "id": "balc_sky_terrace_v2_rail_front",
      "position": [
        0.0,
        7.95,
        6.8
      ],
      "size": [
        8.4,
        1.1
      ],
      "rotationY": 0.0,
      "floorLevel": 2,
      "handrail": true
    },
    {
      "id": "balc_sky_terrace_v2_rail_left",
      "position": [
        -4.2,
        7.95,
        4.5
      ],
      "size": [
        4.6,
        1.1
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 2,
      "handrail": true
    },
    {
      "id": "balc_sky_terrace_v2_rail_right",
      "position": [
        4.2,
        7.95,
        4.5
      ],
      "size": [
        4.6,
        1.1
      ],
      "rotationY": 1.5707963267948966,
      "floorLevel": 2,
      "handrail": true
    }
  ],
  "focalTargets": {
    "living": {
      "target": [
        0.0,
        2.2,
        0.5
      ],
      "theta": 0.45,
      "phi": 1.05,
      "radius": 16.0,
      "walk": [
        -1.0,
        1.65,
        3.2
      ]
    },
    "kitchen": {
      "target": [
        7.6,
        1.6,
        0.0
      ],
      "theta": 1.95,
      "phi": 1.05,
      "radius": 13.0,
      "walk": [
        6.5,
        1.65,
        1.2
      ]
    },
    "pool_deck": {
      "target": [
        0.0,
        1.2,
        8.0
      ],
      "theta": 2.2,
      "phi": 1.1,
      "radius": 14.0,
      "walk": [
        0.0,
        1.65,
        6.5
      ]
    },
    "master": {
      "target": [
        -6.5,
        4.8,
        0.5
      ],
      "theta": 0.45,
      "phi": 1.05,
      "radius": 14.0,
      "walk": [
        -5.2,
        5.35,
        1.8
      ]
    },
    "mezzanine": {
      "target": [
        0.0,
        4.8,
        -2.0
      ],
      "theta": 0.85,
      "phi": 1.05,
      "radius": 12.0,
      "walk": [
        0.0,
        5.35,
        -1.0
      ]
    },
    "bedroom_2": {
      "target": [
        6.8,
        4.8,
        0.5
      ],
      "theta": 1.85,
      "phi": 1.08,
      "radius": 13.0,
      "walk": [
        5.2,
        5.35,
        1.8
      ]
    },
    "bedroom_3": {
      "target": [
        -5.0,
        8.5,
        -0.5
      ],
      "theta": 0.45,
      "phi": 1.08,
      "radius": 13.0,
      "walk": [
        -3.8,
        9.05,
        1.2
      ]
    },
    "bedroom_4": {
      "target": [
        5.0,
        8.5,
        -0.5
      ],
      "theta": 1.85,
      "phi": 1.08,
      "radius": 13.0,
      "walk": [
        3.8,
        9.05,
        1.2
      ]
    },
    "sky_terrace": {
      "target": [
        0.0,
        8.5,
        4.5
      ],
      "theta": 2.25,
      "phi": 1.05,
      "radius": 14.0,
      "walk": [
        0.0,
        9.05,
        3.2
      ]
    },
    "all": {
      "target": [
        0.0,
        2.8,
        0.0
      ],
      "theta": 0.72,
      "phi": 1.05,
      "radius": 34.0,
      "walk": [
        0.0,
        1.65,
        12.0
      ]
    }
  },
  "waypoints": [
    {
      "p": [
        4.0,
        3.5,
        18.0
      ],
      "l": [
        0.0,
        2.5,
        0.0
      ],
      "label": "Approach · Golfshire Fairway Presidential Villa"
    },
    {
      "p": [
        -1.0,
        1.65,
        3.2
      ],
      "l": [
        2.0,
        1.5,
        -0.5
      ],
      "label": "Ground Floor · Double-Height Living (32' x 24')"
    },
    {
      "p": [
        6.5,
        1.65,
        1.2
      ],
      "l": [
        8.5,
        1.2,
        -1.0
      ],
      "label": "Ground Floor · Gourmet Kitchen Studio (3.09:1 Ratio)"
    },
    {
      "p": [
        0.0,
        1.65,
        6.5
      ],
      "l": [
        0.0,
        0.8,
        9.5
      ],
      "label": "Ground Floor · Infinity Plunge Pool Deck"
    },
    {
      "p": [
        -5.2,
        5.35,
        1.8
      ],
      "l": [
        -7.8,
        4.6,
        -0.2
      ],
      "label": "1st Floor · Presidential Master Suite (21' x 19')"
    },
    {
      "p": [
        5.2,
        5.35,
        1.8
      ],
      "l": [
        7.8,
        4.6,
        -0.2
      ],
      "label": "1st Floor · Junior Master Suite (18' x 16')"
    },
    {
      "p": [
        -3.8,
        9.05,
        1.2
      ],
      "l": [
        -6.0,
        8.3,
        -1.2
      ],
      "label": "2nd Floor · Sky Villa Suite (Bedroom 3)"
    },
    {
      "p": [
        3.8,
        9.05,
        1.2
      ],
      "l": [
        6.0,
        8.3,
        -1.2
      ],
      "label": "2nd Floor · Penthouse Suite (Bedroom 4)"
    },
    {
      "p": [
        18.0,
        16.0,
        18.0
      ],
      "l": [
        0.0,
        3.0,
        0.0
      ],
      "label": "Aerial · Full 3D Spatial Digital Twin"
    }
  ],
  "fixtures": [
    {
      "item": "4 Distinct Bedroom Suites",
      "detail": "Accurately mapped with Master Suite + 3 secondary suites",
      "included": true
    },
    {
      "item": "Calibrated 3:1 Living Hall to Kitchen Ratio",
      "detail": "Grand entertainment volume with dedicated ergonomic culinary studio",
      "included": true
    },
    {
      "item": "Structural BIM Perimeter & Partition Walls",
      "detail": "Full height architectural walls with proper openings and skirting",
      "included": true
    },
    {
      "item": "Italian Statuario & Botticino Marble Flooring",
      "detail": "Authentic finish matching database schema (ITALIAN_MARBLE)",
      "included": true
    },
    {
      "item": "Fully Furnished Interior State",
      "detail": "Interior objects moulded directly to FULLY_FURNISHED status",
      "included": true
    },
    {
      "item": "East Sunlight Alignment",
      "detail": "Directional sun and ambient temperature calibrated to EAST",
      "included": true
    },
    {
      "item": "Teak Balconies with Safety Glass Balustrades",
      "detail": "3 bounded exterior balcony systems placed",
      "included": true
    }
  ]
};

export default TEST_VILLA_4BHK_BLUEPRINT;
