import { PropertyListing } from "@/types/property";

export const MOCK_PROPERTIES: PropertyListing[] = [
  {
    id: "prop-1",
    slug: "sobha-silicon-oasis-3bhk",
    title: "Sobha Silicon Oasis 3BHK with Panoramic Balcony & 3D Twin",
    locality: "HSR Layout / Electronic City",
    city: "Bengaluru",
    state: "Karnataka",
    coordinates: { lat: 12.8596, lng: 77.6534 },
    listingMode: "BUY",
    category: ["DIRECT_OWNER", "DIGITAL_TWIN", "TOP_AVM_DEALS", "TRUST_PASS_ELITE", "GATED_COMMUNITIES", "RERA_APPROVED"],
    propertyType: "Apartment",
    configuration: "3 BHK",
    bathrooms: 3,
    carpetAreaSqft: 1540,
    superBuiltUpAreaSqft: 1850,
    floor: "8th of 14 Floors",
    facing: "East",
    waterSupply: "Cauvery + Borewell",
    pricePaise: "1850000000", // 1.85 Cr
    formattedPrice: "₹1.85 Cr",
    pricePerSqft: "₹10,000 / sq.ft",
    maintenanceMonthlyPaise: "650000", // ₹6,500/mo
    stampDutyEstimate: "₹10,36,000 (5.6%)",
    registrationEstimate: "₹1,85,000 (1%)",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80",
    ],
    has3dTour: true,
    spatialRooms: [
      { id: "living", name: "Formal Living & Dining", dimensions: "22' x 16'", carpetSqft: 352, highlight: "Italian Botticino marble floor, triple glazed UPVC balcony doors", wallColor: "#F4F1EA", floorType: "Imported Marble" },
      { id: "master", name: "Master Suite with Walk-In", dimensions: "18' x 14'", carpetSqft: 252, highlight: "Engineered German oak wood flooring with private garden sit-out", wallColor: "#EAE7DF", floorType: "Engineered Oak" },
      { id: "kitchen", name: "Modular Island Kitchen", dimensions: "14' x 11'", carpetSqft: 154, highlight: "Quartz countertop, built-in Bosch dishwasher and chimney", wallColor: "#F8F8F8", floorType: "Anti-skid Vitrified" },
      { id: "terrace", name: "Covered Sky Balcony", dimensions: "16' x 7'", carpetSqft: 112, highlight: "Unobstructed lakefront vista, vertical herb planter grid", wallColor: "#E8ECE9", floorType: "Rustic Terracotta" },
    ],
    trustScore: 96,
    verifiedOwnerBadge: true,
    topBadge: "Owner Verified · Grade A",
    ulpin: "2919-0412-8831-01",
    reraNumber: "PRM/KA/RERA/1251/310/PR/171015/000412",
    availableFrom: "Immediate / Ready to Move",
    inspection: {
      id: "insp-8841",
      inspectorName: "Er. Ramesh S. Rao, M.Tech Civil (NICMAR)",
      inspectionDate: "15 Feb 2026",
      scores: {
        composite: 96,
        structural: 98,
        plumbing: 94,
        electrical: 91,
        finishes: 95,
        cadastral: 99,
      },
      verifiedPointsCount: 80,
      seepageDetected: false,
      activeLiens: false,
      ulpin: "2919-0412-8831-01",
      summary: "Exceptional structural resilience (M35 design grade confirmed by rebound hammer test). Absolutely zero active dampness or efflorescence across all wet zones. 100% clean 30-year deed chain on Kaveri 2.0 with zero encumbrance.",
      keyFindings: [
        { category: "Structural & RCC", status: "PASS", detail: "Rebound hammer test showed 38.2 N/mm² compressive strength (Standard: >30 N/mm²). No deflection." },
        { category: "Plumbing & Moisture", status: "PASS", detail: "FLIR thermal moisture test recorded 8.4% relative dampness (Well below 15% threshold). Drain slopes optimal." },
        { category: "Electrical Safety", status: "PASS", detail: "Residual Current Circuit Breaker (RCCB) trip latency clocked at 22ms. Earth pit resistance 1.4 Ohms." },
        { category: "Cadastral / Legal", status: "OPTIMAL", detail: "ULPIN 2919-0412-8831-01 matched perfectly to Survey No. 42/1B. EC Form 15 clean through 1996–2026." },
      ],
      pdfUrl: "/reports/sobha-silicon-oasis-80pt-audit.pdf",
    },
    valuation: {
      fairMarketPricePaise: "1920000000", // ₹1.92 Cr
      listedPricePaise: "1850000000",
      differencePercentage: -3.6, // 3.6% discount
      marketPosition: "BELOW_AVM",
      grossYieldPercentage: 4.6,
      monthlyRentalEstimatePaise: "6800000", // ₹68,000/mo
      projected5YrAppreciation: "+38% (HSR Metro Yellow Line Extension)",
      historicalTransactionsCount: 14,
    },
    deedHistory: [
      { year: "2026", eventType: "INSPECTION_AUDIT", title: "80-Point Physical Civil & Spatial Twin Audit", parties: "Amberstone Engineering Bureau", status: "VERIFIED" },
      { year: "2023", eventType: "ULPIN_SEEDED", title: "Digitized Cadastral Seeding (ULPIN 2919-0412-8831-01)", parties: "Kaveri 2.0 Karnataka Revenue Dept", status: "VERIFIED" },
      { year: "2019", eventType: "ENCUMBRANCE_CLEARED", title: "Mortgage Satisfaction & NOC Certificate", parties: "HDFC Bank Ltd → Owner", status: "CLEARED" },
      { year: "2016", eventType: "SALE_DEED", title: "Registered Absolute Sale Deed (Doc #4928/2016)", parties: "Sobha Developers Ltd → S. Venkatraman", volumeNumber: "Vol 412, Pgs 88-104", status: "VERIFIED" },
    ],
    owner: {
      id: "own-101",
      fullName: "S. Venkatraman",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      kycStatus: "DIGILOCKER_VERIFIED",
      joinedDate: "October 2024",
      responseTime: "< 45 minutes",
      phoneMasked: "+91 98450 •••••",
      unredactedPhone: "+91 98450 49122",
      unredactedWhatsApp: "+91 98450 49122",
    },
    amenities: [
      "Clubhouse & 25m Heated Lap Pool",
      "24/7 Power Backup (100% DG)",
      "Dedicated EV 7.4kW Fast Charger",
      "Kaveri Water Supply Direct",
      "Badminton & Squash Courts",
      "Biometric Access Lobby",
      "Children's Play Area & Crèche",
      "Solar Water Heating",
    ],
    neighbourhood: {
      metroDistanceMeters: 550,
      schoolsNearby: ["Delhi Public School (1.2 km)", "National Public School HSR (2.4 km)"],
      hospitalNearby: "Manipal Hospital Sarjapur (1.8 km)",
      waterSecurityIndex: "High (94/100) — Dual Cauvery + Rainwater Harvesting",
    },
  },
  {
    id: "prop-2",
    slug: "prestige-golfshire-luxury-villa",
    title: "Prestige Golfshire 4BHK Fairway Villa with Private Plunge Pool",
    locality: "Nandi Hills / Devanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    coordinates: { lat: 13.3702, lng: 77.6835 },
    listingMode: "BUY",
    category: ["DIRECT_OWNER", "DIGITAL_TWIN", "TRUST_PASS_ELITE", "VILLAS_PLOTS", "RERA_APPROVED"],
    propertyType: "Villa",
    configuration: "4 BHK",
    bathrooms: 5,
    carpetAreaSqft: 3800,
    superBuiltUpAreaSqft: 4500,
    floor: "G + 2 Independent Villa",
    facing: "North-East",
    waterSupply: "Borewell + RO",
    pricePaise: "4500000000", // 4.50 Cr
    formattedPrice: "₹4.50 Cr",
    pricePerSqft: "₹10,000 / sq.ft",
    maintenanceMonthlyPaise: "1800000",
    stampDutyEstimate: "₹25,20,000 (5.6%)",
    registrationEstimate: "₹4,50,000 (1%)",
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80",
    ],
    has3dTour: true,
    spatialRooms: [
      { id: "living", name: "Double-Height Grand Living", dimensions: "28' x 20'", carpetSqft: 560, highlight: "22ft floor-to-ceiling glass looking out to Championship 18-hole Golf Course", wallColor: "#FBF9F5", floorType: "Greek Thassos White Marble" },
      { id: "pool", name: "Private Heated Plunge Pool & Deck", dimensions: "24' x 12'", carpetSqft: 288, highlight: "Balinese Sukabumi stone tiles with infinity overflow edge", wallColor: "#0F2B36", floorType: "Teak Wood Decking" },
      { id: "master", name: "Presidential Master Suite", dimensions: "22' x 18'", carpetSqft: 396, highlight: "Wrap-around golf course balcony and jacuzzi pavilion", wallColor: "#ECEAE4", floorType: "Natural Walnut Hardwood" },
      { id: "kitchen", name: "Siemens Integrated Gourmet Kitchen", dimensions: "16' x 14'", carpetSqft: 224, highlight: "Corian central island with wine chiller & induction downdraft", wallColor: "#FFFFFF", floorType: "Honed Quartzite" },
    ],
    trustScore: 98,
    verifiedOwnerBadge: true,
    topBadge: "Top 1% Trust Score · Villa",
    ulpin: "2920-5519-7723-04",
    reraNumber: "PRM/KA/RERA/1250/303/PR/171123/000551",
    availableFrom: "Immediate",
    inspection: {
      id: "insp-8842",
      inspectorName: "Er. K. Narayana Murthy, Chartered Structural Engineer",
      inspectionDate: "20 Jan 2026",
      scores: {
        composite: 98,
        structural: 99,
        plumbing: 97,
        electrical: 96,
        finishes: 98,
        cadastral: 100,
      },
      verifiedPointsCount: 80,
      seepageDetected: false,
      activeLiens: false,
      ulpin: "2920-5519-7723-04",
      summary: "Pristine private villa development. Flawless foundation raft depth and seismic zone II compliance. Rainwater holding tank capacity 25,000L fully operational.",
      keyFindings: [
        { category: "Structural & RCC", status: "PASS", detail: "Ultrasonic pulse velocity (UPV) test clocked 4.65 km/s (Graded Excellent Quality RCC)." },
        { category: "Plumbing & Moisture", status: "PASS", detail: "Pressure test on CPVC lines at 10 bar for 4 hours held without loss." },
        { category: "Cadastral", status: "OPTIMAL", detail: "Absolute freehold title. Revenue survey boundary pegged with DGPS precision markers." },
      ],
      pdfUrl: "/reports/prestige-golfshire-villa-audit.pdf",
    },
    valuation: {
      fairMarketPricePaise: "4650000000",
      listedPricePaise: "4500000000",
      differencePercentage: -3.2,
      marketPosition: "BELOW_AVM",
      grossYieldPercentage: 3.8,
      monthlyRentalEstimatePaise: "14000000", // ₹1.40L/mo
      projected5YrAppreciation: "+44% (Airport corridor expansion)",
      historicalTransactionsCount: 8,
    },
    deedHistory: [
      { year: "2026", eventType: "INSPECTION_AUDIT", title: "Civil 80-Pt Audit & 3D Spatial Capture", parties: "Amberstone Physical Assurance", status: "VERIFIED" },
      { year: "2024", eventType: "ULPIN_SEEDED", title: "Cadastral Geo-boundary Verified", parties: "Karnataka Land Records", status: "VERIFIED" },
      { year: "2018", eventType: "SALE_DEED", title: "Absolute Sale Deed (Registered)", parties: "Prestige Estates Projects Ltd → Dr. Ananya Sen", status: "VERIFIED" },
    ],
    owner: {
      id: "own-102",
      fullName: "Dr. Ananya Sen",
      avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80",
      kycStatus: "DIGILOCKER_VERIFIED",
      joinedDate: "January 2025",
      responseTime: "< 1 hour",
      phoneMasked: "+91 97312 •••••",
      unredactedPhone: "+91 97312 88401",
      unredactedWhatsApp: "+91 97312 88401",
    },
    amenities: [
      "18-Hole PGA Standard Golf Course",
      "Helipad Access on Request",
      "Falcon Greens 5-Star Club & Spa",
      "Private Heated Plunge Pool",
      "Tesla/EV Level-2 Fast Charger",
      "24/7 Armed Society Perimeter Patrol",
      "Water Filtration & RO Plant",
    ],
    neighbourhood: {
      metroDistanceMeters: 4800,
      schoolsNearby: ["Stonehill International School (4.5 km)", "Canadian International School (8 km)"],
      hospitalNearby: "Aster CMI Hospital Hebbal (18 mins via Expressway)",
      waterSecurityIndex: "High (96/100) — Multi-tier Rainwater + Water Treatment",
    },
  },
  {
    id: "prop-3",
    slug: "lodha-world-towers-3bhk",
    title: "Lodha World One 3BHK with Arabian Sea View & Armani Interiors",
    locality: "Lower Parel",
    city: "Mumbai",
    state: "Maharashtra",
    coordinates: { lat: 18.9986, lng: 72.8311 },
    listingMode: "BUY",
    category: ["DIRECT_OWNER", "DIGITAL_TWIN", "TOP_AVM_DEALS", "TRUST_PASS_ELITE", "GATED_COMMUNITIES"],
    propertyType: "Apartment",
    configuration: "3 BHK",
    bathrooms: 4,
    carpetAreaSqft: 1820,
    superBuiltUpAreaSqft: 2280,
    floor: "42nd of 76 Floors",
    facing: "West",
    waterSupply: "Cauvery Direct", // BMC direct
    pricePaise: "6800000000", // 6.80 Cr
    formattedPrice: "₹6.80 Cr",
    pricePerSqft: "₹37,362 / sq.ft",
    maintenanceMonthlyPaise: "3200000", // ₹32,000/mo
    stampDutyEstimate: "₹40,80,000 (6%)",
    registrationEstimate: "₹30,000",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80",
    ],
    has3dTour: true,
    spatialRooms: [
      { id: "living", name: "Grand Salon with Sea Vista", dimensions: "26' x 18'", carpetSqft: 468, highlight: "Floor-to-ceiling curved double glazing framing the Arabian Sea skyline", wallColor: "#FAF8F5", floorType: "Imported Calacatta Gold" },
      { id: "master", name: "Armani / Casa Master Suite", dimensions: "20' x 16'", carpetSqft: 320, highlight: "Leather panelled headboard wall with en-suite standalone jacuzzi", wallColor: "#ECE7E1", floorType: "Engineered Smoked Oak" },
      { id: "kitchen", name: "Poggenpohl Culinary Studio", dimensions: "15' x 12'", carpetSqft: 180, highlight: "Miele induction appliances and sub-zero twin refrigeration", wallColor: "#FFFFFF", floorType: "Nero Marquina Marble" },
    ],
    trustScore: 97,
    verifiedOwnerBadge: true,
    topBadge: "Owner Direct · High Rise",
    ulpin: "2701-8842-1920-03",
    reraNumber: "P51900008962",
    availableFrom: "Ready to Move",
    inspection: {
      id: "insp-8843",
      inspectorName: "Er. Vikram Kulkarni, PE Structural (Mumbai)",
      inspectionDate: "10 Feb 2026",
      scores: {
        composite: 97,
        structural: 98,
        plumbing: 96,
        electrical: 98,
        finishes: 97,
        cadastral: 98,
      },
      verifiedPointsCount: 80,
      seepageDetected: false,
      activeLiens: false,
      ulpin: "2701-8842-1920-03",
      summary: "Benchmark seismic wind-tunnel certified engineering. Zero wall dampness at high altitude (42nd floor). BMC water pressure continuous at 3.5 bar with multi-level pressure regulators.",
      keyFindings: [
        { category: "Wind & Structural", status: "PASS", detail: "Aero-dynamic damper tuned mass system functioning in specifications. Nil structural vibration." },
        { category: "Facade Glazing", status: "PASS", detail: "Acoustic attenuation measured 42dB reduction from street noise. Argon filled IGU panes intact." },
      ],
      pdfUrl: "/reports/lodha-world-one-audit.pdf",
    },
    valuation: {
      fairMarketPricePaise: "7100000000",
      listedPricePaise: "6800000000",
      differencePercentage: -4.2,
      marketPosition: "BELOW_AVM",
      grossYieldPercentage: 4.1,
      monthlyRentalEstimatePaise: "23000000", // ₹2.3L/mo
      projected5YrAppreciation: "+32% (Coastal Road & Worli Sea Link synergy)",
      historicalTransactionsCount: 19,
    },
    deedHistory: [
      { year: "2026", eventType: "INSPECTION_AUDIT", title: "80-Point Structural & Spatial Twin Verified", parties: "Amberstone Physical Assurance", status: "VERIFIED" },
      { year: "2021", eventType: "SALE_DEED", title: "Registered Deed of Conveyance", parties: "Lodha World Crest P Ltd → Cyrus Mistry Trust", volumeNumber: "BOM-4281", status: "VERIFIED" },
    ],
    owner: {
      id: "own-103",
      fullName: "Cyrus M. Mehta",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      kycStatus: "DIGILOCKER_VERIFIED",
      joinedDate: "December 2024",
      responseTime: "< 30 minutes",
      phoneMasked: "+91 98200 •••••",
      unredactedPhone: "+91 98200 77192",
      unredactedWhatsApp: "+91 98200 77192",
    },
    amenities: [
      "Armani / Casa Designed Sky Lounge",
      "Six Senses Luxury Spa & Hydrotherapy Pool",
      "Private Screening Cinema (24 Seats)",
      "Helipad & Chauffeur Waiting Lounge",
      "Direct High-Speed Elevators (6 m/s)",
      "24/7 Concierge by Quintessentially",
    ],
    neighbourhood: {
      metroDistanceMeters: 400,
      schoolsNearby: ["The Cathedral & John Connon (15 mins)", "Bombay Scottish (18 mins)"],
      hospitalNearby: "Jaslok Hospital & Breach Candy (12 mins)",
      waterSecurityIndex: "High (98/100) — Direct BMC high-capacity reservoirs",
    },
  },
  {
    id: "prop-4",
    slug: "total-environment-windmills-4bhk",
    title: "Total Environment Windmills of Your Mind 4BHK Duplex with Earth Terrace",
    locality: "Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    coordinates: { lat: 12.9815, lng: 77.7289 },
    listingMode: "BUY",
    category: ["DIRECT_OWNER", "DIGITAL_TWIN", "TOP_AVM_DEALS", "TRUST_PASS_ELITE", "GATED_COMMUNITIES", "HIGH_RENTAL_YIELD"],
    propertyType: "Apartment",
    configuration: "4 BHK",
    bathrooms: 4,
    carpetAreaSqft: 2980,
    superBuiltUpAreaSqft: 3750,
    floor: "11th & 12th Floor Duplex",
    facing: "East",
    waterSupply: "Cauvery + Borewell",
    pricePaise: "3950000000", // 3.95 Cr
    formattedPrice: "₹3.95 Cr",
    pricePerSqft: "₹10,533 / sq.ft",
    maintenanceMonthlyPaise: "1400000",
    stampDutyEstimate: "₹22,12,000 (5.6%)",
    registrationEstimate: "₹3,95,000 (1%)",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    has3dTour: true,
    spatialRooms: [
      { id: "living", name: "Duplex Earth Living Room", dimensions: "24' x 18'", carpetSqft: 432, highlight: "Exposed wire-cut brickwork, Kota stone floors, and private lawn terrace garden", wallColor: "#C96D46", floorType: "Fine Honed Kota Stone" },
      { id: "garden", name: "Landscaped Terrace Garden", dimensions: "20' x 12'", carpetSqft: 240, highlight: "Real turf lawn, Frangipani tree, automated drip irrigation system", wallColor: "#4B6B58", floorType: "Natural Green Grass & Slate" },
      { id: "master", name: "Upper Level Master Suite", dimensions: "20' x 16'", carpetSqft: 320, highlight: "Solid teak woodwork and private reading loft", wallColor: "#EDE7DC", floorType: "Solid Teak Wood" },
    ],
    trustScore: 95,
    verifiedOwnerBadge: true,
    topBadge: "Owner Verified · Duplex",
    ulpin: "2919-7734-9012-05",
    reraNumber: "PRM/KA/RERA/1251/446/PR/171015/000219",
    availableFrom: "Immediate",
    inspection: {
      id: "insp-8844",
      inspectorName: "Er. Arvind Hegde, B.E Civil, Structural Specialist",
      inspectionDate: "28 Jan 2026",
      scores: {
        composite: 95,
        structural: 97,
        plumbing: 93,
        electrical: 94,
        finishes: 98,
        cadastral: 96,
      },
      verifiedPointsCount: 80,
      seepageDetected: false,
      activeLiens: false,
      ulpin: "2919-7734-9012-05",
      summary: "Craftsmanship benchmark. Terrace waterproofing tested with 72-hour standing water ponding test with 0% seepage below. Brickwork mortar joints sound.",
      keyFindings: [
        { category: "Terrace Waterproofing", status: "PASS", detail: "72-hour ponding test at 100mm water depth showed zero deflection or capillary absorption." },
        { category: "Carpentry & Joinery", status: "OPTIMAL", detail: "Custom wire-cut brick and handcrafted solid brass fittings inspected and graded pristine." },
      ],
      pdfUrl: "/reports/windmills-of-your-mind-audit.pdf",
    },
    valuation: {
      fairMarketPricePaise: "4100000000",
      listedPricePaise: "3950000000",
      differencePercentage: -3.6,
      marketPosition: "BELOW_AVM",
      grossYieldPercentage: 4.9,
      monthlyRentalEstimatePaise: "16000000", // ₹1.60L/mo
      projected5YrAppreciation: "+35% (Kadugodi Metro Purple Line operational)",
      historicalTransactionsCount: 11,
    },
    deedHistory: [
      { year: "2026", eventType: "INSPECTION_AUDIT", title: "Amberstone Physical & 3D Spatial Audit", parties: "Amberstone Field Assurance", status: "VERIFIED" },
      { year: "2023", eventType: "ULPIN_SEEDED", title: "Kaveri 2.0 Cadastral Parcel ID Mapped", parties: "Govt of Karnataka", status: "VERIFIED" },
      { year: "2017", eventType: "SALE_DEED", title: "Original Tripartite Sale Agreement", parties: "Total Environment Building Systems → R. Jayashankar", status: "VERIFIED" },
    ],
    owner: {
      id: "own-104",
      fullName: "R. Jayashankar",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      kycStatus: "DIGILOCKER_VERIFIED",
      joinedDate: "November 2024",
      responseTime: "< 1 hour",
      phoneMasked: "+91 99001 •••••",
      unredactedPhone: "+91 99001 22849",
      unredactedWhatsApp: "+91 99001 22849",
    },
    amenities: [
      "Private Earth Terrace Garden with Automatic Sprinklers",
      "Microbrewery on Premises",
      "Heated Swimming Pool & Tennis Court",
      "100% Centralized Water Softening",
      "Fibre to the Home & Smart Home Automation",
    ],
    neighbourhood: {
      metroDistanceMeters: 800,
      schoolsNearby: ["The International School Bangalore (6 km)", "Inventure Academy (7 km)"],
      hospitalNearby: "Manipal Hospital Whitefield (1.4 km)",
      waterSecurityIndex: "High (92/100) — On-site deep aquifer & tertiary treatment",
    },
  },
  {
    id: "prop-5",
    slug: "puravankara-silicon-heights-rent",
    title: "Puravankara Heights 3BHK Fully Furnished with Balcony Garden",
    locality: "Indiranagar / 100ft Road",
    city: "Bengaluru",
    state: "Karnataka",
    coordinates: { lat: 12.9719, lng: 77.6412 },
    listingMode: "RENT",
    category: ["DIRECT_OWNER", "DIGITAL_TWIN", "TOP_AVM_DEALS", "TRUST_PASS_ELITE", "HIGH_RENTAL_YIELD"],
    propertyType: "Apartment",
    configuration: "3 BHK",
    bathrooms: 3,
    carpetAreaSqft: 1450,
    superBuiltUpAreaSqft: 1720,
    floor: "6th of 10 Floors",
    facing: "North",
    waterSupply: "Cauvery + Borewell",
    pricePaise: "7500000", // ₹75,000 / month
    formattedPrice: "₹75,000 / mo",
    pricePerSqft: "₹43 / sq.ft / mo",
    maintenanceMonthlyPaise: "550000", // ₹5,500/mo
    images: [
      "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005229762-ee1b2b9cb1f2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    has3dTour: true,
    spatialRooms: [
      { id: "living", name: "Scandinavian Styled Living", dimensions: "20' x 14'", carpetSqft: 280, highlight: "Ash wood entertainment unit, plush linen couch, and balcony overlooking tree canopies", wallColor: "#F5F5F0", floorType: "Vitrified Matte Tile" },
      { id: "kitchen", name: "Modern Island Kitchen", dimensions: "12' x 10'", carpetSqft: 120, highlight: "Faber chimney, Samsung refrigerator, reverse osmosis water filtration unit", wallColor: "#FFFFFF", floorType: "Ceramic Ceramic" },
    ],
    trustScore: 96,
    verifiedOwnerBadge: true,
    topBadge: "Zero Brokerage · Verified Owner",
    ulpin: "2919-5561-3321-08",
    availableFrom: "Immediate / Move In",
    inspection: {
      id: "insp-8845",
      inspectorName: "Er. Deepa Nair, Lead Civil Quality Inspector",
      inspectionDate: "12 Feb 2026",
      scores: {
        composite: 96,
        structural: 98,
        plumbing: 95,
        electrical: 96,
        finishes: 94,
        cadastral: 98,
      },
      verifiedPointsCount: 80,
      seepageDetected: false,
      activeLiens: false,
      ulpin: "2919-5561-3321-08",
      summary: "Turnkey ready rental. Freshly repainted with Asian Paints Royale zero-VOC paint. All split ACs serviced with new filters. Zero plumbing drips.",
      keyFindings: [
        { category: "HVAC & Appliances", status: "PASS", detail: "3 Daikin Inverter ACs tested at 18°C; coil pressure and wattage verified within nominal limits." },
        { category: "Water Hardness", status: "OPTIMAL", detail: "TDS measured at 145 ppm (ideal drinking water range). Cauvery municipal inlet clean." },
      ],
      pdfUrl: "/reports/puravankara-indiranagar-audit.pdf",
    },
    valuation: {
      fairMarketPricePaise: "8000000", // ₹80k fair rent
      listedPricePaise: "7500000",
      differencePercentage: -6.2,
      marketPosition: "BELOW_AVM",
      projected5YrAppreciation: "Rental Yield: 4.9% p.a.",
      historicalTransactionsCount: 22,
    },
    deedHistory: [
      { year: "2026", eventType: "INSPECTION_AUDIT", title: "Rental Handover Civil & Appliance Audit", parties: "Amberstone Inspection Team", status: "VERIFIED" },
      { year: "2022", eventType: "KHATA_TRANSFER", title: "BBMP e-Khata Certificate (PID 082-W0014)", parties: "Bruhat Bengaluru Mahanagara Palike", status: "VERIFIED" },
    ],
    owner: {
      id: "own-105",
      fullName: "Pooja V. Shenoy",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
      kycStatus: "DIGILOCKER_VERIFIED",
      joinedDate: "August 2024",
      responseTime: "< 20 minutes",
      phoneMasked: "+91 98802 •••••",
      unredactedPhone: "+91 98802 61993",
      unredactedWhatsApp: "+91 98802 61993",
    },
    amenities: [
      "100% Power Backup for Full Flat",
      "High-speed 300 Mbps Fibre Installed",
      "Covered Reserved Stilt Car Parking",
      "Swimming Pool & Gymnasium",
      "Walk to 100ft Road Metro & Breweries",
    ],
    neighbourhood: {
      metroDistanceMeters: 450,
      schoolsNearby: ["Frank Anthony Public School (1.8 km)", "National Public School Indiranagar (1.2 km)"],
      hospitalNearby: "Chinmaya Mission Hospital (700m)",
      waterSecurityIndex: "High (96/100) — Direct municipal Cauvery pipeline",
    },
  },
  {
    id: "prop-6",
    slug: "brigade-gateway-lakeview-2bhk",
    title: "Brigade Gateway 2BHK with Orion Mall & Lake View",
    locality: "Malleshwaram / Rajajinagar",
    city: "Bengaluru",
    state: "Karnataka",
    coordinates: { lat: 13.0118, lng: 77.5556 },
    listingMode: "BUY",
    category: ["DIRECT_OWNER", "TOP_AVM_DEALS", "GATED_COMMUNITIES", "RERA_APPROVED"],
    propertyType: "Apartment",
    configuration: "2 BHK",
    bathrooms: 2,
    carpetAreaSqft: 980,
    superBuiltUpAreaSqft: 1280,
    floor: "14th of 19 Floors",
    facing: "North",
    waterSupply: "Cauvery Direct",
    pricePaise: "1420000000", // 1.42 Cr
    formattedPrice: "₹1.42 Cr",
    pricePerSqft: "₹11,093 / sq.ft",
    maintenanceMonthlyPaise: "450000",
    stampDutyEstimate: "₹7,95,200 (5.6%)",
    registrationEstimate: "₹1,42,000 (1%)",
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448205-4d9b3e6bb6db?auto=format&fit=crop&w=1200&q=80",
    ],
    has3dTour: false,
    trustScore: 94,
    verifiedOwnerBadge: true,
    topBadge: "Owner Verified · High Demand",
    ulpin: "2918-1102-3942-02",
    reraNumber: "PRM/KA/RERA/1251/309/PR/171015/000102",
    availableFrom: "Ready to Move",
    inspection: {
      id: "insp-8846",
      inspectorName: "Er. Ramesh S. Rao, M.Tech Civil",
      inspectionDate: "18 Jan 2026",
      scores: {
        composite: 94,
        structural: 96,
        plumbing: 93,
        electrical: 93,
        finishes: 92,
        cadastral: 98,
      },
      verifiedPointsCount: 80,
      seepageDetected: false,
      activeLiens: false,
      ulpin: "2918-1102-3942-02",
      summary: "Grade A integrated township. Structural condition is exemplary with sound joint sealing. Cauvery water connection running with certified water meter.",
      keyFindings: [
        { category: "Structure", status: "PASS", detail: "Nil microcracks or shear cracks in external masonry walls." },
        { category: "Electrical", status: "PASS", detail: "Siemens MCB distribution box certified; no phase imbalance." },
      ],
      pdfUrl: "/reports/brigade-gateway-audit.pdf",
    },
    valuation: {
      fairMarketPricePaise: "1480000000",
      listedPricePaise: "1420000000",
      differencePercentage: -4.0,
      marketPosition: "BELOW_AVM",
      grossYieldPercentage: 4.4,
      monthlyRentalEstimatePaise: "5200000",
      projected5YrAppreciation: "+28%",
      historicalTransactionsCount: 26,
    },
    deedHistory: [
      { year: "2026", eventType: "INSPECTION_AUDIT", title: "80-Point Physical Verification Audit", parties: "Amberstone Civil Engineers", status: "VERIFIED" },
      { year: "2015", eventType: "SALE_DEED", title: "Absolute Sale Deed", parties: "Brigade Enterprises Ltd → Murali Krishnan", status: "VERIFIED" },
    ],
    owner: {
      id: "own-106",
      fullName: "Murali Krishnan",
      avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
      kycStatus: "DIGILOCKER_VERIFIED",
      joinedDate: "September 2024",
      responseTime: "< 1 hour",
      phoneMasked: "+91 94480 •••••",
      unredactedPhone: "+91 94480 33921",
      unredactedWhatsApp: "+91 94480 33921",
    },
    amenities: [
      "Integrated Orion Mall Skywalk",
      "World Trade Centre Commercial Hub",
      "Columbia Asia (Manipal) Hospital On-Site",
      "Lake Promenade & Running Track",
      "Sandalwood Metro Station at Doorstep",
    ],
    neighbourhood: {
      metroDistanceMeters: 150,
      schoolsNearby: ["Cluny Convent (800m)", "Kendriya Vidyalaya IISc (1.5 km)"],
      hospitalNearby: "Manipal Hospital inside campus (100m)",
      waterSecurityIndex: "High (95/100) — Direct Cauvery pipeline + Dedicated STP",
    },
  },
  {
    id: "prop-7",
    slug: "oberoi-sky-city-penthouse",
    title: "Oberoi Sky City 4BHK Penthouse with Private Sky Deck",
    locality: "Borivali East",
    city: "Mumbai",
    state: "Maharashtra",
    coordinates: { lat: 19.2241, lng: 72.8643 },
    listingMode: "BUY",
    category: ["DIRECT_OWNER", "DIGITAL_TWIN", "TRUST_PASS_ELITE", "GATED_COMMUNITIES", "RERA_APPROVED"],
    propertyType: "Penthouse",
    configuration: "4 BHK",
    bathrooms: 5,
    carpetAreaSqft: 2600,
    superBuiltUpAreaSqft: 3200,
    floor: "58th of 60 Floors",
    facing: "East",
    waterSupply: "Cauvery Direct", // BMC direct
    pricePaise: "5200000000", // 5.20 Cr
    formattedPrice: "₹5.20 Cr",
    pricePerSqft: "₹16,250 / sq.ft",
    maintenanceMonthlyPaise: "2200000",
    stampDutyEstimate: "₹31,20,000 (6%)",
    registrationEstimate: "₹30,000",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    has3dTour: true,
    spatialRooms: [
      { id: "sky-deck", name: "Panoramic Sky Deck & Lounge", dimensions: "28' x 16'", carpetSqft: 448, highlight: "Double height sky lounge with cantilevered glass balcony overlooking Sanjay Gandhi National Park", wallColor: "#F4F2EC", floorType: "Flamed Slate & Teak Deck" },
      { id: "living", name: "Grand Penthouse Salon", dimensions: "24' x 20'", carpetSqft: 480, highlight: "Italian Statuario marble with German Schüco acoustic floor-to-ceiling facade", wallColor: "#ECEAE4", floorType: "Statuario Marble" },
      { id: "master", name: "Presidential Master Suite", dimensions: "22' x 16'", carpetSqft: 352, highlight: "Walk-in wardrobe, private Jacuzzi pavilion, sunset orientation", wallColor: "#EDE7DC", floorType: "Smoked Chevron Oak" },
    ],
    trustScore: 96,
    verifiedOwnerBadge: true,
    topBadge: "Top 1% Trust Score · Penthouse",
    ulpin: "2701-6677-4433-11",
    reraNumber: "P51800003582",
    availableFrom: "Immediate",
    inspection: {
      id: "insp-8847",
      inspectorName: "Er. Vikram Kulkarni, PE Structural",
      inspectionDate: "05 Feb 2026",
      scores: {
        composite: 96,
        structural: 98,
        plumbing: 95,
        electrical: 96,
        finishes: 97,
        cadastral: 98,
      },
      verifiedPointsCount: 80,
      seepageDetected: false,
      activeLiens: false,
      ulpin: "2701-6677-4433-11",
      summary: "Pristine sky home. Unrestricted panoramic view of Sanjay Gandhi National Park. High-grade Schüco acoustic facade withstands monsoon wind pressures effortlessly.",
      keyFindings: [
        { category: "Facade Glazing", status: "PASS", detail: "Schüco German thermal break windows certified leak-proof up to 2500 Pa wind pressure." },
      ],
      pdfUrl: "/reports/oberoi-sky-city-audit.pdf",
    },
    valuation: {
      fairMarketPricePaise: "5450000000",
      listedPricePaise: "5200000000",
      differencePercentage: -4.6,
      marketPosition: "BELOW_AVM",
      grossYieldPercentage: 3.9,
      monthlyRentalEstimatePaise: "17000000",
      projected5YrAppreciation: "+34%",
      historicalTransactionsCount: 15,
    },
    deedHistory: [
      { year: "2026", eventType: "INSPECTION_AUDIT", title: "80-Point Civil & Digital Twin Inspection", parties: "Amberstone Assurance", status: "VERIFIED" },
      { year: "2020", eventType: "SALE_DEED", title: "Registered Deed of Conveyance", parties: "Oberoi Realty Ltd → Rajesh Poddar", status: "VERIFIED" },
    ],
    owner: {
      id: "own-107",
      fullName: "Rajesh Poddar",
      avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80",
      kycStatus: "DIGILOCKER_VERIFIED",
      joinedDate: "October 2024",
      responseTime: "< 40 minutes",
      phoneMasked: "+91 98211 •••••",
      unredactedPhone: "+91 98211 40992",
      unredactedWhatsApp: "+91 98211 40992",
    },
    amenities: [
      "25-Acre Integrated Master Planned Development",
      "Private Sky Deck with National Park Views",
      "Olympic Size Swimming Pool & Badminton Courts",
      "Direct Metro Station Connectivity at Podium",
      "Electric Vehicle Multi-Charger Infrastructure",
    ],
    neighbourhood: {
      metroDistanceMeters: 200,
      schoolsNearby: ["Oberoi International School (3 km)", "St. Francis D'Assisi (2 km)"],
      hospitalNearby: "Apex Superspeciality Hospital (1.5 km)",
      waterSecurityIndex: "High (96/100)",
    },
  },
  {
    id: "prop-8",
    slug: "embassy-pristine-lakeview-rent",
    title: "Embassy Pristine 3BHK Overlooking Agara Lake & Wildlife Sanctuary",
    locality: "Koramangala / Iblur",
    city: "Bengaluru",
    state: "Karnataka",
    coordinates: { lat: 12.9234, lng: 77.6542 },
    listingMode: "RENT",
    category: ["DIRECT_OWNER", "DIGITAL_TWIN", "TOP_AVM_DEALS", "TRUST_PASS_ELITE", "HIGH_RENTAL_YIELD"],
    propertyType: "Apartment",
    configuration: "3 BHK",
    bathrooms: 3,
    carpetAreaSqft: 1850,
    superBuiltUpAreaSqft: 2200,
    floor: "9th of 16 Floors",
    facing: "North-East",
    waterSupply: "Cauvery + Borewell",
    pricePaise: "9000000", // ₹90,000 / month
    formattedPrice: "₹90,000 / mo",
    pricePerSqft: "₹41 / sq.ft / mo",
    maintenanceMonthlyPaise: "750000", // ₹7,500/mo
    images: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80",
    ],
    has3dTour: true,
    spatialRooms: [
      { id: "lake-living", name: "Lakefront Living & Balcony", dimensions: "22' x 15'", carpetSqft: 330, highlight: "Unrestricted panoramic vista of Agara lake sanctuary with motorized acoustic shades", wallColor: "#F5F5F0", floorType: "Imported Vitrified" },
      { id: "master", name: "Lake-facing Master Suite", dimensions: "18' x 14'", carpetSqft: 252, highlight: "East facing morning light with cross-ventilation corridor", wallColor: "#EDEBE6", floorType: "Engineered Hardwood" },
      { id: "kitchen", name: "Modular Island Kitchen", dimensions: "14' x 10'", carpetSqft: 140, highlight: "Hafele hardware with piped gas and stainless steel breakfast counter", wallColor: "#FFFFFF", floorType: "Ceramic Anti-skid" },
    ],
    trustScore: 95,
    verifiedOwnerBadge: true,
    topBadge: "Owner Direct · Zero Brokerage",
    ulpin: "2919-9943-1287-09",
    availableFrom: "Within 15 Days",
    inspection: {
      id: "insp-8848",
      inspectorName: "Er. Deepa Nair, Lead Civil Quality Inspector",
      inspectionDate: "02 Feb 2026",
      scores: {
        composite: 95,
        structural: 97,
        plumbing: 94,
        electrical: 95,
        finishes: 96,
        cadastral: 98,
      },
      verifiedPointsCount: 80,
      seepageDetected: false,
      activeLiens: false,
      ulpin: "2919-9943-1287-09",
      summary: "IGBC Gold certified green home. Excellent cross-ventilation facing uninterrupted protected lake sanctuary. All electrical wiring & fixtures Megger tested.",
      keyFindings: [
        { category: "Ventilation & Air", status: "OPTIMAL", detail: "Natural cross air changes measure 8 per hour. Zero mustiness." },
      ],
      pdfUrl: "/reports/embassy-pristine-audit.pdf",
    },
    valuation: {
      fairMarketPricePaise: "9500000",
      listedPricePaise: "9000000",
      differencePercentage: -5.3,
      marketPosition: "BELOW_AVM",
      projected5YrAppreciation: "Gross Yield: 5.1% p.a.",
      historicalTransactionsCount: 17,
    },
    deedHistory: [
      { year: "2026", eventType: "INSPECTION_AUDIT", title: "Civil 80-Pt & Zero-Seepage Audit", parties: "Amberstone Field Assurance", status: "VERIFIED" },
      { year: "2019", eventType: "SALE_DEED", title: "Registered Absolute Sale Deed", parties: "Embassy Group → K. Radhakrishnan", status: "VERIFIED" },
    ],
    owner: {
      id: "own-108",
      fullName: "K. Radhakrishnan",
      avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80",
      kycStatus: "DIGILOCKER_VERIFIED",
      joinedDate: "July 2024",
      responseTime: "< 1 hour",
      phoneMasked: "+91 98455 •••••",
      unredactedPhone: "+91 98455 12890",
      unredactedWhatsApp: "+91 98455 12890",
    },
    amenities: [
      "Uninterrupted Agara Lakefront Views",
      "IGBC Gold Rated Green Building",
      "Heated Indoor Pool & Squash Courts",
      "Zero Water Runoff Zero Waste Society",
      "Adjacent to Outer Ring Road Tech Parks",
    ],
    neighbourhood: {
      metroDistanceMeters: 600,
      schoolsNearby: ["Bethany High School (2.5 km)", "Greenwood High Preschool (800m)"],
      hospitalNearby: "Sakra World Hospital (3 km)",
      waterSecurityIndex: "High (96/100)",
    },
  },
];
